/**
 * Route definitions — migrated from src/domain/play/routeTemplates.ts.
 *
 * Phase 1b sub-deliverable. Each route is a 1:1 port of its legacy
 * RouteTemplate entry. The legacy file becomes auto-generated in
 * Phase 1c (`scripts/fb-kg/generate-route-templates.ts`).
 *
 * Migration choices:
 *   - All routes apply to all 4 game variants (proportional normalization
 *     handles field-width differences). Variant filtering happens at
 *     concept level, not route level.
 *   - `description` (KG) = short 1-sentence summary.
 *   - `body` (KG) = full legacy `description` field — becomes the
 *     rag_documents KB chunk content.
 *   - `kbSubtopic` carried over verbatim — generators use this as the
 *     SQL row key.
 */

import type { RouteDef } from "../schemas/RouteDef";

const ALL_VARIANTS = ["flag_5v5", "flag_6v6", "flag_7v7", "tackle_11"] as const;

export const ROUTES: RouteDef[] = [
  // ── Verticals ──────────────────────────────────────────────────────
  {
    id: "go",
    name: "Go",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Straight vertical sprint downfield — no break, full speed, ball over the top.",
    body: "Straight vertical sprint downfield (route tree #9). No break — full-speed release, accelerate upfield, ball thrown over the top. Stretches the defense vertically. Best vs single-high coverage with no deep help.",
    aliases: ["Fly", "Streak", "Vertical", "9"],
    complexity: "basic",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.55 },
    ],
    shapes: ["straight"],
    breakStyle: "none",
    breakDir: "vertical",
    constraints: { depthRangeYds: { min: 10, max: 25 }, side: "vertical" },
    kbSubtopic: "route_go",
  },
  {
    id: "seam",
    name: "Seam",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Vertical sprint from a slot or TE splitting the deep safeties — slight inside release.",
    body: "Vertical sprint from a slot or TE alignment, splitting the deep safeties. No hard break — slight inside release, then sustained vertical. Beats Cover 2 (gap between safeties) and Cover 4 (vertical the safety can't carry). Foundation route in 4 verts.",
    complexity: "basic",
    directional: true,
    // Inside release at the stem (-0.02), then RESET to vertical (x=0
    // at the final waypoint). Earlier version held x=-0.04 through to
    // the end, which scaled to 2.1yd lateral drift at 18yd depth —
    // the validator's "Seam must finish within 1.5yd vertically of
    // the player's x" check rejected it (Four Verticals + Dagger in
    // tackle_11, surfaced 2026-05-24 cross-variant test). The visual
    // character ("slight inside release then vertical") is preserved
    // because the middle waypoint still moves inside; the final point
    // pulls back to the player's x so the route reads as vertical.
    points: [
      { x: 0, y: 0 },
      { x: -0.02, y: 0.06 },
      { x: 0, y: 0.55 },
    ],
    shapes: ["straight", "straight"],
    breakStyle: "none",
    breakDir: "vertical",
    constraints: { depthRangeYds: { min: 10, max: 25 }, side: "vertical" },
    kbSubtopic: "route_seam",
  },
  {
    id: "fade",
    name: "Fade",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Vertical release with a rounded outside arc — back-shoulder ball.",
    body: "Vertical release with a ROUNDED outside arc toward the sideline (no hard break). Ball thrown back-shoulder or up-and-away. Red-zone staple — defender can't recover when the throw is placed up-and-away. Usually a tall WR vs a short DB.",
    complexity: "intermediate",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0.06, y: 0.22 },
      { x: 0.14, y: 0.52 },
    ],
    shapes: ["curve", "curve"],
    breakStyle: "rounded",
    breakDir: "toward_sideline",
    constraints: { depthRangeYds: { min: 10, max: 22 }, side: "toward_sideline" },
    kbSubtopic: "route_fade",
  },

  // ── Sharp breaks (in/out family) ──────────────────────────────────
  {
    id: "slant",
    name: "Slant",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "3-yard stem then sharp inside cut at ~25° above horizontal — catches at 5-6 yds.",
    body: "3-yard vertical stem then a SHARP 25°-above-horizontal cut across the middle (angle measured from horizontal — mostly lateral with a shallow upfield lean, NOT a steep vertical-leaning break). Catches at 5-6 yds depth, having gained 5-7 yds laterally (route tree #2). Beats press man (inside leverage fast) and Cover 2 (slant fits between underneath defenders).",
    complexity: "basic",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.12 },
      { x: -0.20, y: 0.232 },
    ],
    shapes: ["straight", "straight"],
    breakStyle: "sharp",
    breakDir: "toward_qb",
    constraints: { depthRangeYds: { min: 3, max: 7 }, side: "toward_qb" },
    kbSubtopic: "route_slant",
  },
  {
    id: "out",
    name: "Out",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Vertical 10 yds then sharp 90° break to the sideline — stops the clock.",
    body: "Vertical 10 yards then a SHARP 90° break toward the sideline (route tree #3). Stops the clock — common late-game call. Vulnerable to a jumping cornerback if undisguised.",
    aliases: ["Square-Out"],
    complexity: "basic",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.40 },
      { x: 0.20, y: 0.40 },
    ],
    shapes: ["straight", "straight"],
    breakStyle: "sharp",
    breakDir: "toward_sideline",
    constraints: { depthRangeYds: { min: 8, max: 12 }, side: "toward_sideline" },
    kbSubtopic: "route_out",
  },
  {
    id: "in",
    name: "In",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Vertical 8 yds then sharp 90° inside break — sits in front of LBs.",
    body: "Vertical 8 yards then a SHARP 90° break to the inside (toward the QB / middle of the field). Shallower than a Dig — sits in front of the LBs / under the safeties. Common quick-game intermediate vs zone.",
    complexity: "basic",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.32 },
      { x: -0.24, y: 0.32 },
    ],
    shapes: ["straight", "straight"],
    breakStyle: "sharp",
    breakDir: "toward_qb",
    constraints: { depthRangeYds: { min: 6, max: 10 }, side: "toward_qb" },
    kbSubtopic: "route_in",
  },
  {
    id: "quick-out",
    name: "Quick Out",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "5-yard speed out — vertical then sharp 90° to sideline, no break-down.",
    body: "5-yard out — vertical then SHARP 90° break to the sideline at full speed (no break-down). Catches at 4-5 yds. Beats off-man, stops the clock, gets the ball out fast vs pressure.",
    aliases: ["Speed Out"],
    complexity: "basic",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.20 },
      { x: 0.20, y: 0.20 },
    ],
    shapes: ["straight", "straight"],
    breakStyle: "sharp",
    breakDir: "toward_sideline",
    constraints: { depthRangeYds: { min: 4, max: 7 }, side: "toward_sideline" },
    kbSubtopic: "route_quick_out",
  },
  {
    id: "z-out",
    name: "Z-Out",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Deeper Out variant (~7 yds), typically the Z (flanker).",
    body: "Deeper variant of the Out — vertical 7 yds then a SHARP 90° break to the sideline. Typically run by the Z (flanker) when a regular Out's depth is wrong for the timing. Same family as Out (route tree #3); see Route: Out for details.",
    complexity: "intermediate",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.28 },
      { x: 0.22, y: 0.28 },
    ],
    shapes: ["straight", "straight"],
    breakStyle: "sharp",
    breakDir: "toward_sideline",
    constraints: { depthRangeYds: { min: 5, max: 9 }, side: "toward_sideline" },
    kbSubtopic: "route_out",
  },
  {
    id: "z-in",
    name: "Z-In",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Deeper In variant (~7 yds), typically the Z (flanker).",
    body: "Deeper variant of the In — vertical 7 yds then a SHARP 90° break to the inside (toward the QB / middle). Typically run by the Z (flanker) when a regular In's depth is wrong for the timing. Same family as In; see Route: In for details.",
    complexity: "intermediate",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.28 },
      { x: -0.28, y: 0.28 },
    ],
    shapes: ["straight", "straight"],
    breakStyle: "sharp",
    breakDir: "toward_qb",
    constraints: { depthRangeYds: { min: 5, max: 9 }, side: "toward_qb" },
    kbSubtopic: "route_in",
  },

  // ── Deep breaks (post/corner/dig) ─────────────────────────────────
  {
    id: "post",
    name: "Post",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Vertical 11-12 yds then sharp 45° inside break toward goalpost.",
    body: "Vertical 11-12 yards then a SHARP 45°-above-horizontal break inside toward the goalpost / middle of the field (route tree #8). Beats single-high (Cover 1, Cover 3) when the safety bites, and beats Cover 2 between the safeties. Pair with a deep crosser to clear the safety.",
    complexity: "intermediate",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.44 },
      { x: -0.18, y: 0.62 },
    ],
    shapes: ["straight", "straight"],
    breakStyle: "sharp",
    breakDir: "toward_qb",
    constraints: { depthRangeYds: { min: 10, max: 18 }, side: "toward_qb" },
    kbSubtopic: "route_post",
  },
  {
    id: "corner",
    name: "Corner",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Vertical 11-12 yds then sharp 45° outside break toward back pylon.",
    body: "Vertical 11-12 yards then a SHARP 45°-above-horizontal break outside toward the back pylon (route tree #7). Beats Cover 2 (corner sits flat) and Cover 4 (corner stays inside on outside #1). Often the high in a smash concept.",
    aliases: ["Flag"],
    complexity: "intermediate",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.44 },
      { x: 0.18, y: 0.62 },
    ],
    shapes: ["straight", "straight"],
    breakStyle: "sharp",
    breakDir: "toward_sideline",
    constraints: { depthRangeYds: { min: 10, max: 18 }, side: "toward_sideline" },
    kbSubtopic: "route_corner",
  },
  {
    id: "dig",
    name: "Dig",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Vertical 12-15 yds then sharp 90° inside break across the middle.",
    body: "Vertical 12-15 yards then a SHARP 90° break to the inside (toward the QB / middle), finishing across the middle (route tree #4). Beats man and zone — sits in the window between LB depth and safety depth. Foundation of dig-post and levels concepts.",
    aliases: ["Square-In"],
    complexity: "intermediate",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.52 },
      { x: -0.30, y: 0.52 },
    ],
    shapes: ["straight", "straight"],
    breakStyle: "sharp",
    breakDir: "toward_qb",
    constraints: { depthRangeYds: { min: 10, max: 16 }, side: "toward_qb" },
    kbSubtopic: "route_dig",
  },
  {
    id: "skinny-post",
    name: "Skinny Post",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Like Post but breaks shallower inside (~70° above horizontal) — beats Cover 3.",
    body: "Vertical 10 yards then a SHALLOW inside break (~70° above horizontal — much closer to vertical than a true 45° post). Beats Cover 3 between the corner and the deep middle safety. Common as the pass option in inside-zone RPOs.",
    aliases: ["Glance"],
    complexity: "advanced",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.40 },
      { x: -0.07, y: 0.60 },
    ],
    shapes: ["straight", "straight"],
    breakStyle: "sharp",
    breakDir: "toward_qb",
    constraints: { depthRangeYds: { min: 10, max: 18 }, side: "toward_qb" },
    kbSubtopic: "route_skinny_post",
  },

  // ── Rounded routes (curl/hitch/sit) ───────────────────────────────
  {
    id: "curl",
    name: "Curl",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Vertical stem then rounded ~180° turn back to QB — settle in zone window.",
    body: "Vertical stem then a ROUNDED ~180° turn back toward the QB, settling in a soft spot in the zone (route tree #6). Canonical depth varies by use: traditional pro-style Curl runs 10-12 yds vertical, settling at ~9 yds; SHORT Curls (5-7 yds vertical, settling at ~5 yds) are the underneath in Curl-Flat / Flood concepts. The catalog accepts ANY depth in [4, 13] — a coach asking for a 7-yard curl is asking for the short variant, not a deviation. The break is a smooth turn-back, NOT a sharp corner — receiver decelerates, faces the QB, and finishes with a slight inside lean toward the middle. Reliable vs zone — find the window between defenders.",
    aliases: ["Hook"],
    complexity: "basic",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.44 },
      { x: -0.04, y: 0.36 },
    ],
    shapes: ["straight", "curve"],
    breakStyle: "rounded",
    breakDir: "toward_qb",
    constraints: { depthRangeYds: { min: 4, max: 13 }, side: "toward_qb" },
    kbSubtopic: "route_curl",
  },
  {
    id: "comeback",
    name: "Comeback",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Vertical 12-13 yds then rounded ~45° break back toward sideline — stops clock.",
    body: "Vertical 12-13 yards then a ROUNDED break back at ~45° toward the sideline, settling at ~10 yds depth (route tree #5). 'Comeback' refers to coming back DOWN in depth, not toward the QB — it's a sideline route. Stops the clock. Defender must drive forward — comeback wins on the cushion.",
    complexity: "intermediate",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.52 },
      { x: 0.10, y: 0.40 },
    ],
    shapes: ["straight", "curve"],
    breakStyle: "rounded",
    breakDir: "toward_sideline",
    constraints: { depthRangeYds: { min: 9, max: 14 }, side: "toward_sideline" },
    kbSubtopic: "route_comeback",
  },
  {
    id: "hitch",
    name: "Hitch",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "5-yd stem then rounded quick turn back to QB — beats off-coverage.",
    body: "5-yard vertical release then a ROUNDED quick turn back toward the QB, settling at 4-5 yds with a slight inside lean (route tree #1). The turn-back is a smooth settle, not a sharp corner. Beats off-coverage instantly. Quick-game staple.",
    complexity: "basic",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.20 },
      { x: -0.02, y: 0.16 },
    ],
    shapes: ["straight", "curve"],
    breakStyle: "rounded",
    breakDir: "toward_qb",
    constraints: { depthRangeYds: { min: 3, max: 6 }, side: "toward_qb" },
    kbSubtopic: "route_hitch",
  },
  {
    id: "sit",
    name: "Sit",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Run to 5-6 yds and settle facing QB — foundation of Stick.",
    body: "Vertical stem to 5-6 yards, then a small ROUNDED settle facing the QB (the receiver stops and turns back). Foundation of the stick concept (with a flat underneath and a clear over the top). Quick-game staple, 3rd-and-medium reliable.",
    aliases: ["Stick"],
    complexity: "basic",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.22 },
      { x: 0, y: 0.18 },
    ],
    shapes: ["straight", "curve"],
    breakStyle: "rounded",
    breakDir: "toward_qb",
    constraints: { depthRangeYds: { min: 3, max: 7 }, side: "toward_qb" },
    kbSubtopic: "route_stick",
  },
  {
    id: "spot",
    name: "Spot",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Inside release to ~5.5 yds, then small rounded settle facing QB.",
    body: "Receiver releases inside on a slight angle, then SETTLES with a small ROUNDED turn-back facing the QB at 5-6 yds depth in a soft spot in the zone. The settle is what defines this route — it is NOT a clean diagonal that ends; the receiver finishes by stopping and squaring up to the QB so he's a ready target. More deliberate than a hitch (longer angled release, deeper sit). Often the inside route in a snag concept (with corner over and flat under).",
    aliases: ["Snag"],
    complexity: "intermediate",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: -0.10, y: 0.22 },
      { x: -0.08, y: 0.20 },
    ],
    shapes: ["straight", "curve"],
    breakStyle: "rounded",
    breakDir: "toward_qb",
    constraints: { depthRangeYds: { min: 3, max: 7 }, side: "toward_qb" },
    kbSubtopic: "route_snag",
  },

  // ── Shallow / lateral ─────────────────────────────────────────────
  {
    id: "drag",
    name: "Drag",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Shallow crossing route at 3-5 yds — foundation of mesh.",
    body: "Shallow crossing route — receiver takes a 1-yard inside release then crosses the formation on a SMOOTH NEARLY-HORIZONTAL ARC at 3-5 yds depth (canonical default ~3yd; can deepen to 7-8yd via depthYds for the OVER drag in a Mesh). The cross itself is at a very shallow angle (~2-3° from horizontal) — the receiver gains essentially no depth as he travels laterally; he is NOT climbing diagonally and the path is NOT a rigid straight line. Coaches reading the diagram should see a HORIZONTAL line across the formation that VISIBLY clears the OL row, not crammed against the LOS. Foundation of mesh, drive, and shallow-cross concepts. Beats man coverage — the defender has to fight through traffic that the offense's other routes generate underneath.",
    aliases: ["Shallow", "Shallow Cross"],
    complexity: "basic",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: -0.05, y: 0.12 },
      { x: -0.20, y: 0.12 },
      { x: -0.45, y: 0.12 },
    ],
    shapes: ["straight", "curve", "curve"],
    breakStyle: "none",
    breakDir: "toward_qb",
    constraints: { depthRangeYds: { min: 1, max: 9 }, side: "toward_qb" },
    kbSubtopic: "route_drag",
  },
  {
    id: "flat",
    name: "Flat",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Nearly horizontal release to sideline at 0-2 yds — RB/slot outlet.",
    body: "Receiver releases on a NEARLY HORIZONTAL path directly to the sideline at 0-2 yds depth — gains very little depth as he travels laterally (the route is FLAT — that's literally the name). Common RB or slot route paired with a curl/corner/sit over the top to high-low the flat defender. The path may arc slightly as the receiver flattens out from the snap angle, but it should NEVER read as a steep climbing diagonal.",
    complexity: "basic",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0.06, y: 0.02 },
      { x: 0.22, y: 0.06 },
    ],
    shapes: ["straight", "curve"],
    breakStyle: "none",
    breakDir: "toward_sideline",
    constraints: { depthRangeYds: { min: 0, max: 4 }, side: "toward_sideline" },
    kbSubtopic: "route_flat",
  },
  {
    id: "arrow",
    name: "Arrow",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Clean diagonal toward flat at ~25° — RB/slot outlet, no break.",
    body: "RB or slot releases on a CLEAN DIAGONAL toward the flat at a shallow angle (~25° from horizontal). Mostly lateral with a small upfield component — finishes ~2-3 yds deep, ~10 yds out (tackle_11 reference). No break, no settle. Outlet for the QB and a natural high-low partner with a sit/curl over the top.",
    complexity: "basic",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0.18, y: 0.10 },
    ],
    shapes: ["straight"],
    breakStyle: "none",
    breakDir: "toward_sideline",
    constraints: { depthRangeYds: { min: 1, max: 5 }, side: "toward_sideline" },
    kbSubtopic: "route_arrow",
  },

  // ── Wheel / Out & Up / multi-move ─────────────────────────────────
  {
    id: "wheel",
    name: "Wheel",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Flat release outside, then rounded turnup vertical along the sideline.",
    body: "RB or slot releases flat to the sideline (~3 yds depth, ~6 yds out), then ROUNDS UP and runs vertical along the sideline (the rounded turnup is the wheel). Beats LBs in man coverage who can't run with a back. Common pair with a deep crosser to clear the safety.",
    complexity: "intermediate",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0.12, y: 0.04 },
      { x: 0.18, y: 0.16 },
      { x: 0.18, y: 0.48 },
    ],
    shapes: ["straight", "curve", "straight"],
    breakStyle: "rounded",
    breakDir: "toward_sideline",
    constraints: { depthRangeYds: { min: 10, max: 22 }, side: "toward_sideline" },
    kbSubtopic: "route_wheel",
  },
  {
    id: "out-and-up",
    name: "Out & Up",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Sell the quick out at 5 yds, then sharply break vertical up the sideline.",
    body: "Sell the quick out at 5 yds, then SHARPLY break vertical up the sideline. Beats corners who jump outs. Effective on the boundary.",
    aliases: ["Out and Up"],
    complexity: "advanced",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.20 },
      { x: 0.18, y: 0.20 },
      { x: 0.18, y: 0.52 },
    ],
    shapes: ["straight", "straight", "straight"],
    breakStyle: "multi",
    breakDir: "toward_sideline",
    constraints: { depthRangeYds: { min: 10, max: 22 }, side: "toward_sideline" },
    kbSubtopic: "route_out_and_up",
  },
  {
    id: "whip",
    name: "Whip",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Fake outward 3-5 yds, then sharply whip back inside on slant angle.",
    body: "Receiver fakes outward (like a quick out) for 3-5 yards, then SHARPLY whips back inside on a slant angle. Misdirection — beats man when defender bites on the out fake. The 'whip' refers to the inside snap-back, finishing toward the QB.",
    aliases: ["Whip-In"],
    complexity: "advanced",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0.10, y: 0.12 },
      { x: -0.16, y: 0.20 },
    ],
    shapes: ["straight", "straight"],
    breakStyle: "multi",
    breakDir: "toward_qb",
    constraints: { depthRangeYds: { min: 4, max: 8 }, side: "toward_qb" },
    kbSubtopic: "route_whip",
  },
  {
    id: "stop-and-go",
    name: "Stop & Go",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Stem 5 yds, fake hitch settle, then release vertical at full speed.",
    body: "Stem 5 yds, fake the hitch (small ROUNDED settle), then release vertical at full speed. Beats off-coverage corners who break aggressively on the hitch. Same family as sluggo (slant-and-go).",
    aliases: ["Sluggo", "Hitch and Go"],
    complexity: "advanced",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0, y: 0.20 },
      { x: 0.04, y: 0.16 },
      { x: 0, y: 0.55 },
    ],
    shapes: ["straight", "curve", "straight"],
    breakStyle: "multi",
    breakDir: "vertical",
    constraints: { depthRangeYds: { min: 12, max: 25 }, side: "vertical" },
    kbSubtopic: "route_hitch_and_go",
  },

  // ── Screens ───────────────────────────────────────────────────────
  {
    id: "bubble",
    name: "Bubble",
    family: "route",
    variants: [...ALL_VARIANTS],
    description: "Backward + outside banana arc — catches behind the LOS in the flat.",
    body: "Receiver releases BACKWARD and outside in a ROUNDED banana arc — apex is 2-3 yds behind the LOS — then arcs forward toward the sideline to catch a quick lateral pass. The deep apex is what makes this a BUBBLE (vs a now screen, which catches at the LOS). Other receivers block downfield. Common RPO tag and quick-perimeter answer.",
    aliases: ["Bubble Screen"],
    complexity: "intermediate",
    directional: true,
    points: [
      { x: 0, y: 0 },
      { x: 0.06, y: -0.10 },
      { x: 0.20, y: -0.04 },
    ],
    shapes: ["curve", "curve"],
    breakStyle: "rounded",
    breakDir: "toward_sideline",
    constraints: { depthRangeYds: { min: -4, max: 1 }, side: "toward_sideline" },
    kbSubtopic: "route_bubble_screen",
  },
];
