/**
 * Scheme definitions — migrated from src/domain/play/defensiveAlignments.ts.
 *
 * Phase 1b sub-deliverable. Each scheme is a 1:1 port of its legacy
 * DefensiveAlignment entry. The legacy file becomes auto-generated in
 * Phase 1c.
 *
 * Migration choices:
 *   - Each scheme is variant-specific (single-entry `variants` array).
 *   - Renames: `players` → `defenders`, `variant` → `variants[]`.
 *   - `description` (KG) = first sentence of legacy description.
 *   - `body` (KG) = full legacy description — becomes the rag_documents
 *     KB chunk content.
 *   - ID convention: `{variant-prefix}-{front-slug}-{coverage-slug}`
 *     where prefix is one of t11/f7/f6/f5.
 */

import type { SchemeDef } from "../schemas/SchemeDef";

export const SCHEMES: SchemeDef[] = [
  // ── Tackle 11 ────────────────────────────────────────────────────
  {
    id: "t11-4-3-over-cover-3",
    name: "4-3 Over · Cover 3",
    family: "scheme",
    variants: ["tackle_11"],
    description: "4-3 Over with the 3-tech to the strong (right) side, Sam walked out over the TE. Cover 3 shell — corners take deep thirds, free safety in the deep middle, three LBs underneath.",
    body: "4-3 Over with the 3-tech to the strong (right) side, Sam walked out over the TE. Cover 3 shell — corners take deep thirds, free safety in the deep middle, three LBs underneath.",
    complexity: "intermediate",
    front: "4-3 Over",
    coverage: "Cover 3",
    defenders: [
      { id: "DE", x: -8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "DT", x: -2,  y: 1, assignment: { kind: "blitz", gap: "A" } },
      { id: "DT", x:  3,  y: 1, assignment: { kind: "blitz", gap: "B" } },
      { id: "DE", x:  8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "WL", x: -5,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "ML", x:  0,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_m" } },
      { id: "SL", x:  6,  y: 4.5, assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "CB", x: -16, y: 6,   assignment: { kind: "zone", zoneId: "deep_third_l" } },
      { id: "CB", x:  16, y: 6,   assignment: { kind: "zone", zoneId: "deep_third_r" } },
      { id: "FS", x:  0,  y: 13,  assignment: { kind: "zone", zoneId: "deep_third_m" } },
      { id: "SS", x:  6,  y: 9,   assignment: { kind: "zone", zoneId: "flat_l" } },
    ],
    zones: [
      { id: "deep_third_l", kind: "ellipse", center: [-11, 17], size: [11, 16], label: "Deep 1/3 L" },
      { id: "deep_third_m", kind: "ellipse", center: [  0, 17], size: [11, 16], label: "Deep 1/3 M" },
      { id: "deep_third_r", kind: "ellipse", center: [ 11, 17], size: [11, 16], label: "Deep 1/3 R" },
      { id: "flat_l",  kind: "ellipse", center: [-14, 4], size: [8,  8], label: "Flat L" },
      { id: "hook_l",  kind: "ellipse", center: [ -5, 5], size: [10, 8], label: "Hook L" },
      { id: "hook_m",  kind: "ellipse", center: [  0, 5], size: [6,  8], label: "Hook M" },
      { id: "flat_r",  kind: "ellipse", center: [ 14, 4], size: [8,  8], label: "Flat R" },
    ],
  },
  {
    id: "t11-4-3-over-cover-2",
    name: "4-3 Over · Cover 2",
    family: "scheme",
    variants: ["tackle_11"],
    description: "4-3 Over front with Cover 2 shell — two safeties splitting the deep halves, corners squat in the flats, three LBs in hook/middle zones.",
    body: "4-3 Over front with Cover 2 shell — two safeties splitting the deep halves, corners squat in the flats, three LBs in hook/middle zones.",
    complexity: "intermediate",
    front: "4-3 Over",
    coverage: "Cover 2",
    defenders: [
      { id: "DE", x: -8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "DT", x: -2,  y: 1, assignment: { kind: "blitz", gap: "A" } },
      { id: "DT", x:  3,  y: 1, assignment: { kind: "blitz", gap: "B" } },
      { id: "DE", x:  8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "WL", x: -5,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "ML", x:  0,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_m" } },
      { id: "SL", x:  6,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_r" } },
      { id: "CB", x: -16, y: 5,   assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "CB", x:  16, y: 5,   assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "FS", x: -8,  y: 13,  assignment: { kind: "zone", zoneId: "deep_half_l" } },
      { id: "SS", x:  8,  y: 13,  assignment: { kind: "zone", zoneId: "deep_half_r" } },
    ],
    zones: [
      { id: "deep_half_l", kind: "ellipse", center: [-8, 17], size: [16, 16], label: "Deep 1/2 L" },
      { id: "deep_half_r", kind: "ellipse", center: [ 8, 17], size: [16, 16], label: "Deep 1/2 R" },
      { id: "flat_l",  kind: "ellipse", center: [-14, 4], size: [8, 8], label: "Flat L" },
      { id: "hook_l",  kind: "ellipse", center: [ -6, 5], size: [7, 8], label: "Hook L" },
      { id: "hook_m",  kind: "ellipse", center: [  0, 5], size: [6, 8], label: "Hook M" },
      { id: "hook_r",  kind: "ellipse", center: [  6, 5], size: [7, 8], label: "Hook R" },
      { id: "flat_r",  kind: "ellipse", center: [ 14, 4], size: [8, 8], label: "Flat R" },
    ],
  },
  {
    id: "t11-3-4-cover-1",
    name: "3-4 · Cover 1",
    family: "scheme",
    variants: ["tackle_11"],
    description: "Three down linemen (NT head-up, two DEs over the tackles), four LBs (two ILBs and two OLBs as edge rushers/setters). Cover 1 — single-high FS, everyone else man.",
    body: "Three down linemen (NT head-up, two DEs over the tackles), four LBs (two ILBs and two OLBs as edge rushers/setters). Cover 1 — single-high FS, everyone else man.",
    complexity: "intermediate",
    front: "3-4",
    coverage: "Cover 1",
    manCoverage: true,
    defenders: [
      { id: "DE", x: -5,  y: 1,   assignment: { kind: "blitz", gap: "B" } },
      { id: "NT", x:  0,  y: 1,   assignment: { kind: "blitz", gap: "A" } },
      { id: "DE", x:  5,  y: 1,   assignment: { kind: "blitz", gap: "B" } },
      { id: "OL", x: -10, y: 2.5, assignment: { kind: "blitz", gap: "edge" } },
      { id: "IL", x: -3,  y: 4.5, assignment: { kind: "man", target: "RB" } },
      { id: "IL", x:  3,  y: 4.5, assignment: { kind: "man", target: "TE" } },
      { id: "OL", x: 10,  y: 2.5, assignment: { kind: "blitz", gap: "edge" } },
      { id: "CB", x: -16, y: 6,   assignment: { kind: "man", target: "X" } },
      { id: "CB", x:  16, y: 6,   assignment: { kind: "man", target: "Z" } },
      { id: "SS", x:  6,  y: 6,   assignment: { kind: "man", target: "Y" } },
      { id: "FS", x:  0,  y: 13,  assignment: { kind: "zone", zoneId: "deep_middle" } },
    ],
    zones: [
      { id: "deep_middle", kind: "ellipse", center: [0, 17], size: [20, 16], label: "Deep middle (FS)" },
    ],
  },
  {
    id: "t11-nickel-425-cover-4",
    name: "Nickel (4-2-5) · Cover 4 Quarters",
    family: "scheme",
    variants: ["tackle_11"],
    description: "Modern nickel front — 4 down, 2 ILBs, 5 DBs (nickel/STAR replaces a LB over the slot). Cover 4 quarters: corners and safeties each take a deep quarter, three underneath.",
    body: "Modern nickel front — 4 down, 2 ILBs, 5 DBs (nickel/STAR replaces a LB over the slot). Cover 4 quarters: corners and safeties each take a deep quarter, three underneath.",
    complexity: "advanced",
    front: "Nickel (4-2-5)",
    coverage: "Cover 4 (Quarters)",
    defenders: [
      { id: "DE", x: -8,  y: 1,   assignment: { kind: "blitz", gap: "edge" } },
      { id: "DT", x: -2,  y: 1,   assignment: { kind: "blitz", gap: "A" } },
      { id: "DT", x:  3,  y: 1,   assignment: { kind: "blitz", gap: "B" } },
      { id: "DE", x:  8,  y: 1,   assignment: { kind: "blitz", gap: "edge" } },
      { id: "ML", x: -3,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_m" } },
      { id: "WL", x:  4,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "NB", x:  9,  y: 5,   assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "CB", x: -16, y: 6,   assignment: { kind: "zone", zoneId: "deep_quarter_1" } },
      { id: "CB", x:  16, y: 6,   assignment: { kind: "zone", zoneId: "deep_quarter_4" } },
      { id: "FS", x: -7,  y: 11,  assignment: { kind: "zone", zoneId: "deep_quarter_2" } },
      { id: "SS", x:  7,  y: 11,  assignment: { kind: "zone", zoneId: "deep_quarter_3" } },
    ],
    zones: [
      { id: "deep_quarter_1", kind: "ellipse", center: [-13.5, 17], size: [9, 16], label: "Deep 1/4" },
      { id: "deep_quarter_2", kind: "ellipse", center: [ -4.5, 17], size: [9, 16], label: "Deep 1/4" },
      { id: "deep_quarter_3", kind: "ellipse", center: [  4.5, 17], size: [9, 16], label: "Deep 1/4" },
      { id: "deep_quarter_4", kind: "ellipse", center: [ 13.5, 17], size: [9, 16], label: "Deep 1/4" },
      { id: "hook_l",  kind: "ellipse", center: [-5, 5], size: [10, 8], label: "Hook L" },
      { id: "hook_m",  kind: "ellipse", center: [ 0, 5], size: [8,  8], label: "Hook M" },
      { id: "flat_r",  kind: "ellipse", center: [12, 4], size: [12, 8], label: "Flat R" },
    ],
  },
  {
    id: "t11-46-bear-cover-1",
    name: "46 Bear · Cover 1",
    family: "scheme",
    variants: ["tackle_11"],
    description: "Bear front — 4 down with both DTs in 3-techs, both DEs wide, strong safety walked into the box. Cover 1 behind it — single-high FS, everyone else man. Crushes the run.",
    body: "Bear front — 4 down with both DTs in 3-techs, both DEs wide, strong safety walked into the box. Cover 1 behind it — single-high FS, everyone else man. Crushes the run.",
    complexity: "advanced",
    front: "46 Bear",
    coverage: "Cover 1",
    manCoverage: true,
    defenders: [
      { id: "DE", x: -10, y: 1,   assignment: { kind: "blitz", gap: "edge" } },
      { id: "DT", x: -3,  y: 1,   assignment: { kind: "blitz", gap: "A" } },
      { id: "DT", x:  3,  y: 1,   assignment: { kind: "blitz", gap: "B" } },
      { id: "DE", x: 10,  y: 1,   assignment: { kind: "blitz", gap: "edge" } },
      { id: "WL", x: -5,  y: 3,   assignment: { kind: "man", target: "RB" } },
      { id: "ML", x:  0,  y: 3,   assignment: { kind: "man", target: "TE" } },
      { id: "SS", x:  5,  y: 3,   assignment: { kind: "man", target: "Y" } },
      { id: "SL", x:  9,  y: 4,   assignment: { kind: "man", target: "S" } },
      { id: "CB", x: -16, y: 6,   assignment: { kind: "man", target: "X" } },
      { id: "CB", x: 16,  y: 6,   assignment: { kind: "man", target: "Z" } },
      { id: "FS", x:  0,  y: 13,  assignment: { kind: "zone", zoneId: "deep_middle" } },
    ],
    zones: [
      { id: "deep_middle", kind: "ellipse", center: [0, 17], size: [20, 16], label: "Deep middle (FS)" },
    ],
  },
  {
    id: "t11-4-4-stack-cover-3",
    name: "4-4 Stack · Cover 3",
    family: "scheme",
    variants: ["tackle_11"],
    description: "Classic 8-in-the-box youth/HS run defense — 4 down linemen + 4 linebackers + 3 DBs.",
    body: "Classic 8-in-the-box youth/HS run defense — 4 down linemen + 4 linebackers (Will, Mike, Buck, Sam) + 3 DBs (2 corners, 1 deep safety in Cover 3). Two ILBs stack directly behind the DTs; two OLBs play just outside the DEs. Heavy run support; vulnerable to spread passing because there are only 3 DBs to cover 4-5 receivers.",
    complexity: "intermediate",
    front: "4-4 Stack",
    coverage: "Cover 3",
    defenders: [
      { id: "DE", x: -8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "DT", x: -3,  y: 1, assignment: { kind: "blitz", gap: "A" } },
      { id: "DT", x:  3,  y: 1, assignment: { kind: "blitz", gap: "B" } },
      { id: "DE", x:  8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "WL", x: -8,  y: 4, assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "ML", x: -3,  y: 4, assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "BK", x:  3,  y: 4, assignment: { kind: "zone", zoneId: "hook_r" } },
      { id: "SL", x:  8,  y: 4, assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "CB", x: -16, y: 6, assignment: { kind: "zone", zoneId: "deep_third_l" } },
      { id: "CB", x:  16, y: 6, assignment: { kind: "zone", zoneId: "deep_third_r" } },
      { id: "FS", x:  0,  y: 13, assignment: { kind: "zone", zoneId: "deep_third_m" } },
    ],
    zones: [
      { id: "deep_third_l", kind: "ellipse", center: [-10, 17], size: [10, 16], label: "Deep 1/3 L" },
      { id: "deep_third_m", kind: "ellipse", center: [  0, 17], size: [10, 16], label: "Deep 1/3 M" },
      { id: "deep_third_r", kind: "ellipse", center: [ 10, 17], size: [10, 16], label: "Deep 1/3 R" },
      { id: "flat_l", kind: "ellipse", center: [-11, 5], size: [8, 8], label: "Flat L" },
      { id: "hook_l", kind: "ellipse", center: [ -4, 5], size: [6, 8], label: "Hook L" },
      { id: "hook_r", kind: "ellipse", center: [  4, 5], size: [6, 8], label: "Hook R" },
      { id: "flat_r", kind: "ellipse", center: [ 11, 5], size: [8, 8], label: "Flat R" },
    ],
  },
  {
    id: "t11-4-4-stack-cover-1",
    name: "4-4 Stack · Cover 1",
    family: "scheme",
    variants: ["tackle_11"],
    description: "8-in-the-box 4-4 with man-free behind it — corners and the 4 LBs in man, single-high FS over the top.",
    body: "8-in-the-box 4-4 with man-free behind it — corners and the 4 LBs in man on the 5 eligible receivers (slot/TE/RB), single-high FS over the top. Aggressive run-support look that asks the LBs to cover backs/TEs man-up.",
    complexity: "intermediate",
    front: "4-4 Stack",
    coverage: "Cover 1",
    manCoverage: true,
    defenders: [
      { id: "DE", x: -8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "DT", x: -3,  y: 1, assignment: { kind: "blitz", gap: "A" } },
      { id: "DT", x:  3,  y: 1, assignment: { kind: "blitz", gap: "B" } },
      { id: "DE", x:  8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "WL", x: -8,  y: 4, assignment: { kind: "man", target: "RB" } },
      { id: "ML", x: -3,  y: 4, assignment: { kind: "man", target: "TE" } },
      { id: "BK", x:  3,  y: 4, assignment: { kind: "man", target: "S" } },
      { id: "SL", x:  8,  y: 4, assignment: { kind: "man", target: "Y" } },
      { id: "CB", x: -16, y: 6, assignment: { kind: "man", target: "X" } },
      { id: "CB", x:  16, y: 6, assignment: { kind: "man", target: "Z" } },
      { id: "FS", x:  0,  y: 13, assignment: { kind: "zone", zoneId: "deep_middle" } },
    ],
    zones: [
      { id: "deep_middle", kind: "ellipse", center: [0, 17], size: [20, 16], label: "Deep middle (FS)" },
    ],
  },

  // ── Flag 7v7 ──────────────────────────────────────────────────────
  {
    id: "f7-cover-3",
    name: "7v7 Zone · Cover 3",
    family: "scheme",
    variants: ["flag_7v7"],
    description: "Standard 7v7 zone shell. 3 deep (corners + free safety), 4 underneath (two flat, two hook).",
    body: "Standard 7v7 zone shell. 3 deep (corners + free safety), 4 underneath (two flat, two hook).",
    complexity: "basic",
    front: "7v7 Zone",
    coverage: "Cover 3",
    defenders: [
      { id: "FL", x: -10, y: 4,  assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "HL", x: -4,  y: 5,  assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "HR", x:  4,  y: 5,  assignment: { kind: "zone", zoneId: "hook_r" } },
      { id: "FR", x: 10,  y: 4,  assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "CB", x: -12, y: 11, assignment: { kind: "zone", zoneId: "deep_third_l" } },
      { id: "FS", x:  0,  y: 13, assignment: { kind: "zone", zoneId: "deep_third_m" } },
      { id: "CB", x: 12,  y: 11, assignment: { kind: "zone", zoneId: "deep_third_r" } },
    ],
    zones: [
      { id: "flat_l",       kind: "ellipse", center: [-11, 5], size: [8,  8], label: "Flat L" },
      { id: "hook_l",       kind: "ellipse", center: [-4,  5], size: [6,  8], label: "Hook L" },
      { id: "hook_r",       kind: "ellipse", center: [ 4,  5], size: [6,  8], label: "Hook R" },
      { id: "flat_r",       kind: "ellipse", center: [11,  5], size: [8,  8], label: "Flat R" },
      { id: "deep_third_l", kind: "ellipse", center: [-10, 17], size: [10, 16], label: "Deep 1/3 L" },
      { id: "deep_third_m", kind: "ellipse", center: [ 0,  17], size: [10, 16], label: "Deep 1/3 M" },
      { id: "deep_third_r", kind: "ellipse", center: [10,  17], size: [10, 16], label: "Deep 1/3 R" },
    ],
  },
  {
    id: "f7-cover-2",
    name: "7v7 Zone · Cover 2",
    family: "scheme",
    variants: ["flag_7v7"],
    description: "7v7 Cover 2 — two safeties split the deep halves, five underneath in zones (two flats, three hooks).",
    body: "7v7 Cover 2 — two safeties split the deep halves, five underneath in zones (two flats, three hooks).",
    complexity: "basic",
    front: "7v7 Zone",
    coverage: "Cover 2",
    defenders: [
      { id: "CB", x: -12, y: 5,  assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "HL", x: -5,  y: 5,  assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "HM", x:  0,  y: 5,  assignment: { kind: "zone", zoneId: "hook_m" } },
      { id: "HR", x:  5,  y: 5,  assignment: { kind: "zone", zoneId: "hook_r" } },
      { id: "CB", x: 12,  y: 5,  assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "FS", x: -7,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_l" } },
      { id: "SS", x:  7,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_r" } },
    ],
    zones: [
      { id: "flat_l", kind: "ellipse", center: [-12, 5], size: [6, 8], label: "Flat L" },
      { id: "hook_l", kind: "ellipse", center: [-5,  5], size: [6, 8], label: "Hook L" },
      { id: "hook_m", kind: "ellipse", center: [ 0,  5], size: [6, 8], label: "Hook M" },
      { id: "hook_r", kind: "ellipse", center: [ 5,  5], size: [6, 8], label: "Hook R" },
      { id: "flat_r", kind: "ellipse", center: [12,  5], size: [6, 8], label: "Flat R" },
      { id: "deep_half_l", kind: "ellipse", center: [-7.5, 17], size: [15, 16], label: "Deep 1/2 L" },
      { id: "deep_half_r", kind: "ellipse", center: [ 7.5, 17], size: [15, 16], label: "Deep 1/2 R" },
    ],
  },
  {
    id: "f7-tampa-2",
    name: "7v7 Zone · Tampa 2",
    family: "scheme",
    variants: ["flag_7v7"],
    description: "7v7 Tampa 2 — Cover 2 shell with the middle hook (M) carrying any vertical down the deep middle.",
    body: "7v7 Tampa 2 — Cover 2 shell with the middle hook (M) carrying any vertical down the deep middle. Effectively a 3-deep, 4-under look out of a 2-high disguise.",
    complexity: "advanced",
    front: "7v7 Zone",
    coverage: "Tampa 2",
    defenders: [
      { id: "CB", x: -12, y: 5,  assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "HL", x: -5,  y: 5,  assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "M",  x:  0,  y: 6,  assignment: { kind: "zone", zoneId: "deep_middle" } },
      { id: "HR", x:  5,  y: 5,  assignment: { kind: "zone", zoneId: "hook_r" } },
      { id: "CB", x: 12,  y: 5,  assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "FS", x: -7,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_l" } },
      { id: "SS", x:  7,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_r" } },
    ],
    zones: [
      { id: "flat_l", kind: "ellipse", center: [-12, 5], size: [6, 8], label: "Flat L" },
      { id: "hook_l", kind: "ellipse", center: [-5,  5], size: [6, 8], label: "Hook L" },
      { id: "hook_r", kind: "ellipse", center: [ 5,  5], size: [6, 8], label: "Hook R" },
      { id: "flat_r", kind: "ellipse", center: [12,  5], size: [6, 8], label: "Flat R" },
      { id: "deep_half_l", kind: "ellipse", center: [-9, 17], size: [12, 16], label: "Deep 1/2 L" },
      { id: "deep_middle", kind: "ellipse", center: [ 0, 17], size: [6,  16], label: "Deep mid (M)" },
      { id: "deep_half_r", kind: "ellipse", center: [ 9, 17], size: [12, 16], label: "Deep 1/2 R" },
    ],
  },
  {
    id: "f7-cover-4",
    name: "7v7 Zone · Cover 4 Quarters",
    family: "scheme",
    variants: ["flag_7v7"],
    description: "7v7 Quarters — four deep defenders each take a quarter of the field, three underneath. Strong vs verticals; soft underneath.",
    body: "7v7 Quarters — four deep defenders each take a quarter of the field, three underneath. Strong vs verticals; soft underneath.",
    complexity: "intermediate",
    front: "7v7 Zone",
    coverage: "Cover 4",
    defenders: [
      { id: "FL", x: -10, y: 5,  assignment: { kind: "zone", zoneId: "curl_flat_l" } },
      { id: "M",  x:   0, y: 5,  assignment: { kind: "zone", zoneId: "hook_m" } },
      { id: "FR", x:  10, y: 5,  assignment: { kind: "zone", zoneId: "curl_flat_r" } },
      { id: "CB", x: -13, y: 11, assignment: { kind: "zone", zoneId: "deep_quarter_1" } },
      { id: "FS", x:  -5, y: 13, assignment: { kind: "zone", zoneId: "deep_quarter_2" } },
      { id: "SS", x:   5, y: 13, assignment: { kind: "zone", zoneId: "deep_quarter_3" } },
      { id: "CB", x:  13, y: 11, assignment: { kind: "zone", zoneId: "deep_quarter_4" } },
    ],
    zones: [
      { id: "curl_flat_l", kind: "ellipse", center: [-10, 5], size: [10, 8], label: "Curl/Flat L" },
      { id: "hook_m",      kind: "ellipse", center: [  0, 5], size: [8,  8], label: "Hook M" },
      { id: "curl_flat_r", kind: "ellipse", center: [ 10, 5], size: [10, 8], label: "Curl/Flat R" },
      { id: "deep_quarter_1", kind: "ellipse", center: [-11, 17], size: [8, 16], label: "Deep 1/4" },
      { id: "deep_quarter_2", kind: "ellipse", center: [ -4, 17], size: [6, 16], label: "Deep 1/4" },
      { id: "deep_quarter_3", kind: "ellipse", center: [  4, 17], size: [6, 16], label: "Deep 1/4" },
      { id: "deep_quarter_4", kind: "ellipse", center: [ 11, 17], size: [8, 16], label: "Deep 1/4" },
    ],
  },
  {
    id: "f7-cover-1",
    name: "7v7 Man · Cover 1",
    family: "scheme",
    variants: ["flag_7v7"],
    description: "7v7 man-free — six defenders in man on the six skill receivers, single-high FS over the top.",
    body: "7v7 man-free — six defenders in man on the six skill receivers, single-high FS over the top.",
    complexity: "basic",
    front: "7v7 Man",
    coverage: "Cover 1",
    manCoverage: true,
    defenders: [
      { id: "CB", x: -12, y: 5,  assignment: { kind: "man", target: "X" } },
      { id: "NB", x: -6,  y: 5,  assignment: { kind: "man", target: "H" } },
      { id: "LB", x:  0,  y: 4,  assignment: { kind: "man", target: "B" } },
      { id: "NB", x:  6,  y: 5,  assignment: { kind: "man", target: "S" } },
      { id: "CB", x: 12,  y: 5,  assignment: { kind: "man", target: "Z" } },
      { id: "SS", x:  4,  y: 6,  assignment: { kind: "man", target: "Y" } },
      { id: "FS", x:  0,  y: 13, assignment: { kind: "zone", zoneId: "deep_middle" } },
    ],
    zones: [
      { id: "deep_middle", kind: "ellipse", center: [0, 17], size: [20, 16], label: "Deep middle (FS)" },
    ],
  },
  {
    id: "f7-cover-0",
    name: "7v7 Man · Cover 0",
    family: "scheme",
    variants: ["flag_7v7"],
    description: "7v7 Cover 0 — every defender in pure man, no deep help. Rare, used to bait an aggressive throw or on critical down/distance.",
    body: "7v7 Cover 0 — every defender in pure man, no deep help. Rare, used to bait an aggressive throw or on critical down/distance.",
    complexity: "advanced",
    front: "7v7 Man",
    coverage: "Cover 0",
    manCoverage: true,
    defenders: [
      { id: "CB", x: -12, y: 5, assignment: { kind: "man", target: "X" } },
      { id: "NB", x: -6,  y: 5, assignment: { kind: "man", target: "H" } },
      { id: "LB", x:  0,  y: 4, assignment: { kind: "man", target: "B" } },
      { id: "NB", x:  6,  y: 5, assignment: { kind: "man", target: "S" } },
      { id: "CB", x: 12,  y: 5, assignment: { kind: "man", target: "Z" } },
      { id: "SS", x:  6,  y: 6, assignment: { kind: "man", target: "Y" } },
      { id: "FS", x: -4,  y: 6, assignment: { kind: "spy", target: "Q" } },
    ],
    zones: [],
  },

  // ── Flag 6v6 ──────────────────────────────────────────────────────
  {
    id: "f6-cover-3",
    name: "6v6 Zone · Cover 3",
    family: "scheme",
    variants: ["flag_6v6"],
    description: "6v6 zone shell — 3 deep (two corners + free safety), 2 underneath (flat/hook on each side), edge rusher off the line.",
    body: "6v6 zone shell — 3 deep (two corners + free safety), 2 underneath (flat/hook on each side), edge rusher off the line.",
    complexity: "basic",
    front: "6v6 Zone",
    coverage: "Cover 3",
    defenders: [
      { id: "E",  x:  4,  y: 2,  assignment: { kind: "blitz", gap: "edge" } },
      { id: "FL", x: -8,  y: 4,  assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "FR", x:  8,  y: 4,  assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "CB", x: -11, y: 11, assignment: { kind: "zone", zoneId: "deep_third_l" } },
      { id: "FS", x:  0,  y: 13, assignment: { kind: "zone", zoneId: "deep_third_m" } },
      { id: "CB", x: 11,  y: 11, assignment: { kind: "zone", zoneId: "deep_third_r" } },
    ],
    zones: [
      { id: "flat_l", kind: "ellipse", center: [-9, 4], size: [8, 8], label: "Flat L" },
      { id: "flat_r", kind: "ellipse", center: [ 9, 4], size: [8, 8], label: "Flat R" },
      { id: "deep_third_l", kind: "ellipse", center: [-10, 17], size: [10, 16], label: "Deep 1/3 L" },
      { id: "deep_third_m", kind: "ellipse", center: [  0, 17], size: [10, 16], label: "Deep 1/3 M" },
      { id: "deep_third_r", kind: "ellipse", center: [ 10, 17], size: [10, 16], label: "Deep 1/3 R" },
    ],
  },
  {
    id: "f6-cover-2",
    name: "6v6 Zone · Cover 2",
    family: "scheme",
    variants: ["flag_6v6"],
    description: "6v6 Cover 2 — two safeties split the deep halves, three underneath in zones (two flats + a middle hook), edge rusher off the line.",
    body: "6v6 Cover 2 — two safeties split the deep halves, three underneath in zones (two flats + a middle hook), edge rusher off the line.",
    complexity: "basic",
    front: "6v6 Zone",
    coverage: "Cover 2",
    defenders: [
      { id: "E",  x:  4,  y: 2,  assignment: { kind: "blitz", gap: "edge" } },
      { id: "CB", x: -10, y: 5,  assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "HM", x:  0,  y: 5,  assignment: { kind: "zone", zoneId: "hook_m" } },
      { id: "CB", x: 10,  y: 5,  assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "FS", x: -6,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_l" } },
      { id: "SS", x:  6,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_r" } },
    ],
    zones: [
      { id: "flat_l", kind: "ellipse", center: [-10, 5], size: [8, 8], label: "Flat L" },
      { id: "hook_m", kind: "ellipse", center: [  0, 5], size: [8, 8], label: "Hook M" },
      { id: "flat_r", kind: "ellipse", center: [ 10, 5], size: [8, 8], label: "Flat R" },
      { id: "deep_half_l", kind: "ellipse", center: [-7, 17], size: [14, 16], label: "Deep 1/2 L" },
      { id: "deep_half_r", kind: "ellipse", center: [ 7, 17], size: [14, 16], label: "Deep 1/2 R" },
    ],
  },
  {
    id: "f6-cover-1",
    name: "6v6 Man · Cover 1",
    family: "scheme",
    variants: ["flag_6v6"],
    description: "6v6 man-free — four defenders in man on the four skill receivers, one free safety deep, edge rusher off the line.",
    body: "6v6 man-free — four defenders in man on the four skill receivers, one free safety deep, edge rusher off the line.",
    complexity: "basic",
    front: "6v6 Man",
    coverage: "Cover 1",
    manCoverage: true,
    defenders: [
      { id: "E",  x:  4,  y: 2,  assignment: { kind: "blitz", gap: "edge" } },
      { id: "CB", x: -10, y: 5,  assignment: { kind: "man", target: "X" } },
      { id: "NB", x: -4,  y: 5,  assignment: { kind: "man", target: "Y" } },
      { id: "NB", x:  4,  y: 5,  assignment: { kind: "man", target: "S" } },
      { id: "CB", x:  10, y: 5,  assignment: { kind: "man", target: "Z" } },
      { id: "FS", x:  0,  y: 12, assignment: { kind: "zone", zoneId: "deep_middle" } },
    ],
    zones: [
      { id: "deep_middle", kind: "ellipse", center: [0, 17], size: [20, 16], label: "Deep middle (FS)" },
    ],
  },
  {
    id: "f6-cover-0",
    name: "6v6 Man · Cover 0",
    family: "scheme",
    variants: ["flag_6v6"],
    description: "6v6 Cover 0 — every defender in pure man, no deep help. Edge rusher disrupts the QB.",
    body: "6v6 Cover 0 — every defender in pure man, no deep help. Edge rusher disrupts the QB; used to bait an aggressive throw or on critical down/distance.",
    complexity: "advanced",
    front: "6v6 Man",
    coverage: "Cover 0",
    manCoverage: true,
    defenders: [
      { id: "E",  x:  4,  y: 2,  assignment: { kind: "blitz", gap: "edge" } },
      { id: "CB", x: -10, y: 5,  assignment: { kind: "man", target: "X" } },
      { id: "NB", x: -4,  y: 5,  assignment: { kind: "man", target: "Y" } },
      { id: "NB", x:  4,  y: 5,  assignment: { kind: "man", target: "S" } },
      { id: "CB", x:  10, y: 5,  assignment: { kind: "man", target: "Z" } },
      { id: "SS", x:  0,  y: 6,  assignment: { kind: "man", target: "B" } },
    ],
    zones: [],
  },

  // ── Flag 5v5 ──────────────────────────────────────────────────────
  {
    id: "f5-cover-3",
    name: "5v5 Zone · Cover 3",
    family: "scheme",
    variants: ["flag_5v5"],
    description: "5v5 zone shell — 3 deep (two corners + free safety) and 2 underneath (flat/hook on each side).",
    body: "5v5 zone shell — 3 deep (two corners + free safety) and 2 underneath (flat/hook on each side).",
    complexity: "basic",
    front: "5v5 Zone",
    coverage: "Cover 3",
    defenders: [
      { id: "FL", x: -7,  y: 4,  assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "FR", x:  7,  y: 4,  assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "CB", x: -10, y: 10, assignment: { kind: "zone", zoneId: "deep_third_l" } },
      { id: "FS", x:  0,  y: 12, assignment: { kind: "zone", zoneId: "deep_third_m" } },
      { id: "CB", x: 10,  y: 10, assignment: { kind: "zone", zoneId: "deep_third_r" } },
    ],
    zones: [
      { id: "flat_l", kind: "ellipse", center: [-8, 4], size: [10, 8], label: "Flat L" },
      { id: "flat_r", kind: "ellipse", center: [ 8, 4], size: [10, 8], label: "Flat R" },
      { id: "deep_third_l", kind: "ellipse", center: [-9, 17], size: [9, 16], label: "Deep 1/3 L" },
      { id: "deep_third_m", kind: "ellipse", center: [ 0, 17], size: [9, 16], label: "Deep 1/3 M" },
      { id: "deep_third_r", kind: "ellipse", center: [ 9, 17], size: [9, 16], label: "Deep 1/3 R" },
    ],
  },
  {
    id: "f5-cover-1",
    name: "5v5 Man · Cover 1",
    family: "scheme",
    variants: ["flag_5v5"],
    description: "5v5 man — four defenders in man on the four skill players, one free safety deep.",
    body: "5v5 man — four defenders in man on the four skill players, one free safety deep.",
    complexity: "basic",
    front: "5v5 Man",
    coverage: "Cover 1",
    manCoverage: true,
    defenders: [
      { id: "CB", x: -8,  y: 5,  assignment: { kind: "man", target: "X" } },
      { id: "NB", x: -3,  y: 5,  assignment: { kind: "man", target: "H" } },
      { id: "NB", x:  3,  y: 5,  assignment: { kind: "man", target: "S" } },
      { id: "CB", x:  8,  y: 5,  assignment: { kind: "man", target: "Z" } },
      { id: "FS", x:  0,  y: 12, assignment: { kind: "zone", zoneId: "deep_middle" } },
    ],
    zones: [
      { id: "deep_middle", kind: "ellipse", center: [0, 17], size: [20, 16], label: "Deep middle (FS)" },
    ],
  },
];
