/**
 * Scheme definitions — migrated from src/domain/play/defensiveAlignments.ts.
 *
 * Phase 1b sub-deliverable. Each scheme is a 1:1 port of its legacy
 * DefensiveAlignment entry. The legacy file becomes auto-generated in
 * Phase 1c.
 *
 * Migration choices:
 *   - Each scheme is variant-specific (single-entry `variants` array).
 *   - Renames: `players` → `defenders`, `variant` → `variants[]`.
 *   - `description` (KG) = first sentence of legacy description.
 *   - `body` (KG) = full legacy description — becomes the rag_documents
 *     KB chunk content.
 *   - ID convention: `{variant-prefix}-{front-slug}-{coverage-slug}`
 *     where prefix is one of t11/f7/f6/f5.
 */

import type { SchemeDef } from "../schemas/SchemeDef";

export const SCHEMES: SchemeDef[] = [
  // ── Tackle 11 ────────────────────────────────────────────────────
  {
    id: "t11-4-3-over-cover-3",
    name: "4-3 Over · Cover 3",
    family: "scheme",
    variants: ["tackle_11"],
    description: "4-3 Over with the 3-tech to the strong (right) side, Sam walked out over the TE. Cover 3 shell — corners take deep thirds, free safety in the deep middle, three LBs underneath.",
    body: "4-3 Over with the 3-tech to the strong (right) side, Sam walked out over the TE. Cover 3 shell — corners take deep thirds, free safety in the deep middle, three LBs underneath.",
    complexity: "intermediate",
    front: "4-3 Over",
    coverage: "Cover 3",
    whenToUse: "Balanced base call — covers the deep field with a 3-deep shell while keeping 4 underneath defenders + a sound 4-3 run front. Best vs spread teams that mix run and pass; reliable on first/second down when you don't know what's coming.",
    weaknesses: [
      "4 verticals — three deep defenders covering four receivers is math the offense wins. The seam runner splits the safety and the corner.",
      "Smash concept — high-low on the corner stresses the deep third; the corner can't help on the flat and cover the corner route.",
      "Curl-flat on the boundary — the flat defender can't cover both layers; smart QBs pick whichever is uncovered.",
    ],
    defenders: [
      { id: "DE", x: -8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "DT", x: -2,  y: 1, assignment: { kind: "blitz", gap: "A" } },
      { id: "DT", x:  3,  y: 1, assignment: { kind: "blitz", gap: "B" } },
      { id: "DE", x:  8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "WL", x: -5,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "ML", x:  0,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_m" } },
      { id: "SL", x:  6,  y: 4.5, assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "CB", x: -16, y: 6,   assignment: { kind: "zone", zoneId: "deep_third_l" } },
      { id: "CB", x:  16, y: 6,   assignment: { kind: "zone", zoneId: "deep_third_r" } },
      { id: "FS", x:  0,  y: 13,  assignment: { kind: "zone", zoneId: "deep_third_m" } },
      { id: "SS", x:  6,  y: 9,   assignment: { kind: "zone", zoneId: "flat_l" } },
    ],
    zones: [
      { id: "deep_third_l", kind: "ellipse", center: [-11, 17], size: [11, 16], label: "Deep 1/3 L" },
      { id: "deep_third_m", kind: "ellipse", center: [  0, 17], size: [11, 16], label: "Deep 1/3 M" },
      { id: "deep_third_r", kind: "ellipse", center: [ 11, 17], size: [11, 16], label: "Deep 1/3 R" },
      { id: "flat_l",  kind: "ellipse", center: [-14, 4], size: [8,  8], label: "Flat L" },
      { id: "hook_l",  kind: "ellipse", center: [ -5, 5], size: [10, 8], label: "Hook L" },
      { id: "hook_m",  kind: "ellipse", center: [  0, 5], size: [6,  8], label: "Hook M" },
      { id: "flat_r",  kind: "ellipse", center: [ 14, 4], size: [8,  8], label: "Flat R" },
    ],
  },
  {
    id: "t11-4-3-over-cover-2",
    name: "4-3 Over · Cover 2",
    family: "scheme",
    variants: ["tackle_11"],
    description: "4-3 Over front with Cover 2 shell — two safeties splitting the deep halves, corners squat in the flats, three LBs in hook/middle zones.",
    body: "4-3 Over front with Cover 2 shell — two safeties splitting the deep halves, corners squat in the flats, three LBs in hook/middle zones.",
    complexity: "intermediate",
    front: "4-3 Over",
    coverage: "Cover 2",
    whenToUse: "Sideline-coverage shell — corners squat on the flats so quick outs / hitches die. Best vs perimeter-passing teams that live in the underneath, or anytime you want a hard ceiling on chunk plays outside.",
    weaknesses: [
      "Deep middle — no safety on the hash, so 4 verts with a seam runner busts the coverage (the safeties can't cover the middle and the boundary).",
      "Smash concept — the corner/flat conflict on a Cover 2 corner is exactly what Cover 2 invites; the corner over-the-top can't be covered by the safety.",
      "Drives between the hashes — the MLB hook is a long way from a late dig route by the slot.",
    ],
    defenders: [
      { id: "DE", x: -8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "DT", x: -2,  y: 1, assignment: { kind: "blitz", gap: "A" } },
      { id: "DT", x:  3,  y: 1, assignment: { kind: "blitz", gap: "B" } },
      { id: "DE", x:  8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "WL", x: -5,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "ML", x:  0,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_m" } },
      { id: "SL", x:  6,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_r" } },
      { id: "CB", x: -16, y: 5,   assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "CB", x:  16, y: 5,   assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "FS", x: -8,  y: 13,  assignment: { kind: "zone", zoneId: "deep_half_l" } },
      { id: "SS", x:  8,  y: 13,  assignment: { kind: "zone", zoneId: "deep_half_r" } },
    ],
    zones: [
      { id: "deep_half_l", kind: "ellipse", center: [-8, 17], size: [16, 16], label: "Deep 1/2 L" },
      { id: "deep_half_r", kind: "ellipse", center: [ 8, 17], size: [16, 16], label: "Deep 1/2 R" },
      { id: "flat_l",  kind: "ellipse", center: [-14, 4], size: [8, 8], label: "Flat L" },
      { id: "hook_l",  kind: "ellipse", center: [ -6, 5], size: [7, 8], label: "Hook L" },
      { id: "hook_m",  kind: "ellipse", center: [  0, 5], size: [6, 8], label: "Hook M" },
      { id: "hook_r",  kind: "ellipse", center: [  6, 5], size: [7, 8], label: "Hook R" },
      { id: "flat_r",  kind: "ellipse", center: [ 14, 4], size: [8, 8], label: "Flat R" },
    ],
  },
  {
    id: "t11-3-4-cover-1",
    name: "3-4 · Cover 1",
    family: "scheme",
    variants: ["tackle_11"],
    description: "Three down linemen (NT head-up, two DEs over the tackles), four LBs (two ILBs and two OLBs as edge rushers/setters). Cover 1 — single-high FS, everyone else man.",
    body: "Three down linemen (NT head-up, two DEs over the tackles), four LBs (two ILBs and two OLBs as edge rushers/setters). Cover 1 — single-high FS, everyone else man.",
    complexity: "intermediate",
    front: "3-4",
    coverage: "Cover 1",
    manCoverage: true,
    whenToUse: "Pressure call with man coverage and one safety insurance over the top. The 3-4 front gives you OLB flexibility — they can rush off the edge or drop into coverage. Best vs balanced personnel when you trust your DBs in man.",
    weaknesses: [
      "Bunch / picks — switches under stress lead to wide-open receivers behind the rub.",
      "RB / TE on a LB — the smaller, quicker pass-catcher consistently wins those matchups.",
      "Deep verticals to your weakest DB — single-high coverage means no double on the matchup the offense is exploiting.",
      "Interior runs — the 3-4 is light up front (3 DL); A-gap dives and power-A can find creases vs over-aligned DEs.",
    ],
    defenders: [
      { id: "DE", x: -5,  y: 1,   assignment: { kind: "blitz", gap: "B" } },
      { id: "NT", x:  0,  y: 1,   assignment: { kind: "blitz", gap: "A" } },
      { id: "DE", x:  5,  y: 1,   assignment: { kind: "blitz", gap: "B" } },
      { id: "OL", x: -10, y: 2.5, assignment: { kind: "blitz", gap: "edge" } },
      { id: "IL", x: -3,  y: 4.5, assignment: { kind: "man", target: "RB" } },
      { id: "IL", x:  3,  y: 4.5, assignment: { kind: "man", target: "TE" } },
      { id: "OL", x: 10,  y: 2.5, assignment: { kind: "blitz", gap: "edge" } },
      { id: "CB", x: -16, y: 6,   assignment: { kind: "man", target: "X" } },
      { id: "CB", x:  16, y: 6,   assignment: { kind: "man", target: "Z" } },
      { id: "SS", x:  6,  y: 6,   assignment: { kind: "man", target: "Y" } },
      { id: "FS", x:  0,  y: 13,  assignment: { kind: "zone", zoneId: "deep_middle" } },
    ],
    zones: [
      { id: "deep_middle", kind: "ellipse", center: [0, 17], size: [20, 16], label: "Deep middle (FS)" },
    ],
  },
  {
    id: "t11-nickel-425-cover-4",
    name: "Nickel (4-2-5) · Cover 4 Quarters",
    family: "scheme",
    variants: ["tackle_11"],
    description: "Modern nickel front — 4 down, 2 ILBs, 5 DBs (nickel/STAR replaces a LB over the slot). Cover 4 quarters: corners and safeties each take a deep quarter, three underneath.",
    body: "Modern nickel front — 4 down, 2 ILBs, 5 DBs (nickel/STAR replaces a LB over the slot). Cover 4 quarters: corners and safeties each take a deep quarter, three underneath.",
    complexity: "advanced",
    front: "Nickel (4-2-5)",
    coverage: "Cover 4 (Quarters)",
    whenToUse: "Two-high quarters look that morphs into man-match on vertical releases — best vs deep-shot passing teams in must-have-yards situations, or anytime you want a hard ceiling on chunk plays.",
    weaknesses: [
      "Underneath — only 3 zones (or LBs) underneath means the middle is open vs quick game and bubble screens.",
      "Mesh concept — natural pick action at the crossers while the safeties stay deep on their quarters.",
      "Crossers / shallow drag — the LBs are spread thin vs west-coast horizontal stretching.",
      "Light run box — 5 DBs means the front-six can be outnumbered vs spread runs.",
    ],
    defenders: [
      { id: "DE", x: -8,  y: 1,   assignment: { kind: "blitz", gap: "edge" } },
      { id: "DT", x: -2,  y: 1,   assignment: { kind: "blitz", gap: "A" } },
      { id: "DT", x:  3,  y: 1,   assignment: { kind: "blitz", gap: "B" } },
      { id: "DE", x:  8,  y: 1,   assignment: { kind: "blitz", gap: "edge" } },
      { id: "ML", x: -3,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_m" } },
      { id: "WL", x:  4,  y: 4.5, assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "NB", x:  9,  y: 5,   assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "CB", x: -16, y: 6,   assignment: { kind: "zone", zoneId: "deep_quarter_1" } },
      { id: "CB", x:  16, y: 6,   assignment: { kind: "zone", zoneId: "deep_quarter_4" } },
      { id: "FS", x: -7,  y: 11,  assignment: { kind: "zone", zoneId: "deep_quarter_2" } },
      { id: "SS", x:  7,  y: 11,  assignment: { kind: "zone", zoneId: "deep_quarter_3" } },
    ],
    zones: [
      { id: "deep_quarter_1", kind: "ellipse", center: [-13.5, 17], size: [9, 16], label: "Deep 1/4" },
      { id: "deep_quarter_2", kind: "ellipse", center: [ -4.5, 17], size: [9, 16], label: "Deep 1/4" },
      { id: "deep_quarter_3", kind: "ellipse", center: [  4.5, 17], size: [9, 16], label: "Deep 1/4" },
      { id: "deep_quarter_4", kind: "ellipse", center: [ 13.5, 17], size: [9, 16], label: "Deep 1/4" },
      { id: "hook_l",  kind: "ellipse", center: [-5, 5], size: [10, 8], label: "Hook L" },
      { id: "hook_m",  kind: "ellipse", center: [ 0, 5], size: [8,  8], label: "Hook M" },
      { id: "flat_r",  kind: "ellipse", center: [12, 4], size: [12, 8], label: "Flat R" },
    ],
  },
  {
    id: "t11-46-bear-cover-1",
    name: "46 Bear · Cover 1",
    family: "scheme",
    variants: ["tackle_11"],
    description: "Bear front — 4 down with both DTs in 3-techs, both DEs wide, strong safety walked into the box. Cover 1 behind it — single-high FS, everyone else man. Crushes the run.",
    body: "Bear front — 4 down with both DTs in 3-techs, both DEs wide, strong safety walked into the box. Cover 1 behind it — single-high FS, everyone else man. Crushes the run.",
    complexity: "advanced",
    front: "46 Bear",
    coverage: "Cover 1",
    whenToUse: "Extreme pressure scheme — 8-man box with man coverage over receivers. The Bear front (NT + two 3-techs heads-up on every interior OL) is designed to overwhelm the run game and force one-on-one matchups outside.",
    weaknesses: [
      "Spread / 4-WR sets — too many defenders in the box, not enough in coverage. Empty alignment turns the 46 into a free-rusher penalty.",
      "Quick game / RPOs — any 3-step throw beats the Bear front's rush, and the man coverage outside has no help.",
      "Picks and rubs — bunch / mesh concepts exploit the man matchups.",
      "Mismatches — a slot WR on a LB in man is a free completion.",
    ],
    manCoverage: true,
    defenders: [
      { id: "DE", x: -10, y: 1,   assignment: { kind: "blitz", gap: "edge" } },
      { id: "DT", x: -3,  y: 1,   assignment: { kind: "blitz", gap: "A" } },
      { id: "DT", x:  3,  y: 1,   assignment: { kind: "blitz", gap: "B" } },
      { id: "DE", x: 10,  y: 1,   assignment: { kind: "blitz", gap: "edge" } },
      { id: "WL", x: -5,  y: 3,   assignment: { kind: "man", target: "RB" } },
      { id: "ML", x:  0,  y: 3,   assignment: { kind: "man", target: "TE" } },
      { id: "SS", x:  5,  y: 3,   assignment: { kind: "man", target: "Y" } },
      { id: "SL", x:  9,  y: 4,   assignment: { kind: "man", target: "S" } },
      { id: "CB", x: -16, y: 6,   assignment: { kind: "man", target: "X" } },
      { id: "CB", x: 16,  y: 6,   assignment: { kind: "man", target: "Z" } },
      { id: "FS", x:  0,  y: 13,  assignment: { kind: "zone", zoneId: "deep_middle" } },
    ],
    zones: [
      { id: "deep_middle", kind: "ellipse", center: [0, 17], size: [20, 16], label: "Deep middle (FS)" },
    ],
  },
  {
    id: "t11-4-4-stack-cover-3",
    name: "4-4 Stack · Cover 3",
    family: "scheme",
    variants: ["tackle_11"],
    description: "Classic 8-in-the-box youth/HS run defense — 4 down linemen + 4 linebackers + 3 DBs.",
    body: "Classic 8-in-the-box youth/HS run defense — 4 down linemen + 4 linebackers (Will, Mike, Buck, Sam) + 3 DBs (2 corners, 1 deep safety in Cover 3). Two ILBs stack directly behind the DTs; two OLBs play just outside the DEs. Heavy run support; vulnerable to spread passing because there are only 3 DBs to cover 4-5 receivers.",
    complexity: "intermediate",
    front: "4-4 Stack",
    coverage: "Cover 3",
    whenToUse: "Heavy-box run defense with a 3-deep coverage shell. The 4-4 stack puts eight in the box vs run while keeping Cover 3's three-deep distribution. Best vs run-heavy teams that pose a passing-game threat.",
    weaknesses: [
      "4 verts — three deep defenders vs four vertical threats is the same math problem every Cover 3 faces.",
      "Smash / corner-flat conflict — the boundary corner-flat split exposes the same Cover 3 weakness.",
      "Empty / spread looks — the stacked LBs are slow to widen vs 3x1 / 4x1 formations.",
      "Long-developing pass concepts — the 4-4 expects to win on run downs, less suited to obvious passing situations.",
    ],
    defenders: [
      { id: "DE", x: -8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "DT", x: -3,  y: 1, assignment: { kind: "blitz", gap: "A" } },
      { id: "DT", x:  3,  y: 1, assignment: { kind: "blitz", gap: "B" } },
      { id: "DE", x:  8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "WL", x: -8,  y: 4, assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "ML", x: -3,  y: 4, assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "BK", x:  3,  y: 4, assignment: { kind: "zone", zoneId: "hook_r" } },
      { id: "SL", x:  8,  y: 4, assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "CB", x: -16, y: 6, assignment: { kind: "zone", zoneId: "deep_third_l" } },
      { id: "CB", x:  16, y: 6, assignment: { kind: "zone", zoneId: "deep_third_r" } },
      { id: "FS", x:  0,  y: 13, assignment: { kind: "zone", zoneId: "deep_third_m" } },
    ],
    zones: [
      { id: "deep_third_l", kind: "ellipse", center: [-10, 17], size: [10, 16], label: "Deep 1/3 L" },
      { id: "deep_third_m", kind: "ellipse", center: [  0, 17], size: [10, 16], label: "Deep 1/3 M" },
      { id: "deep_third_r", kind: "ellipse", center: [ 10, 17], size: [10, 16], label: "Deep 1/3 R" },
      { id: "flat_l", kind: "ellipse", center: [-11, 5], size: [8, 8], label: "Flat L" },
      { id: "hook_l", kind: "ellipse", center: [ -4, 5], size: [6, 8], label: "Hook L" },
      { id: "hook_r", kind: "ellipse", center: [  4, 5], size: [6, 8], label: "Hook R" },
      { id: "flat_r", kind: "ellipse", center: [ 11, 5], size: [8, 8], label: "Flat R" },
    ],
  },
  {
    id: "t11-4-4-stack-cover-1",
    name: "4-4 Stack · Cover 1",
    family: "scheme",
    variants: ["tackle_11"],
    description: "8-in-the-box 4-4 with man-free behind it — corners and the 4 LBs in man, single-high FS over the top.",
    body: "8-in-the-box 4-4 with man-free behind it — corners and the 4 LBs in man on the 5 eligible receivers (slot/TE/RB), single-high FS over the top. Aggressive run-support look that asks the LBs to cover backs/TEs man-up.",
    complexity: "intermediate",
    front: "4-4 Stack",
    coverage: "Cover 1",
    whenToUse: "Stack-and-blitz: bring an extra man up to either pressure the run or rush the passer, with single-high man coverage on the perimeter. Best when you NEED a stop on a key down vs a balanced run/pass team.",
    weaknesses: [
      "Bunch / picks — single-high man invites rub concepts.",
      "RB / TE on a LB — same Cover 1 weakness — the smaller pass-catcher wins on a route.",
      "Deep verticals to your weakest DB — no help means the targeted matchup is a 50/50 at best.",
      "Spread sets — the heavy box gets in conflict when receivers are split out.",
    ],
    manCoverage: true,
    defenders: [
      { id: "DE", x: -8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "DT", x: -3,  y: 1, assignment: { kind: "blitz", gap: "A" } },
      { id: "DT", x:  3,  y: 1, assignment: { kind: "blitz", gap: "B" } },
      { id: "DE", x:  8,  y: 1, assignment: { kind: "blitz", gap: "edge" } },
      { id: "WL", x: -8,  y: 4, assignment: { kind: "man", target: "RB" } },
      { id: "ML", x: -3,  y: 4, assignment: { kind: "man", target: "TE" } },
      { id: "BK", x:  3,  y: 4, assignment: { kind: "man", target: "S" } },
      { id: "SL", x:  8,  y: 4, assignment: { kind: "man", target: "Y" } },
      { id: "CB", x: -16, y: 6, assignment: { kind: "man", target: "X" } },
      { id: "CB", x:  16, y: 6, assignment: { kind: "man", target: "Z" } },
      { id: "FS", x:  0,  y: 13, assignment: { kind: "zone", zoneId: "deep_middle" } },
    ],
    zones: [
      { id: "deep_middle", kind: "ellipse", center: [0, 17], size: [20, 16], label: "Deep middle (FS)" },
    ],
  },

  // ── Flag 7v7 ──────────────────────────────────────────────────────
  {
    id: "f7-cover-3",
    name: "7v7 Zone · Cover 3",
    family: "scheme",
    variants: ["flag_7v7"],
    description: "Standard 7v7 zone shell. 3 deep (corners + free safety), 4 underneath (two flat, two hook).",
    body: "Standard 7v7 zone shell. 3 deep (corners + free safety), 4 underneath (two flat, two hook).",
    complexity: "basic",
    front: "7v7 Zone",
    coverage: "Cover 3",
    whenToUse: "7v7 zone shell — 3 deep distribution covers the field's vertical thirds; 4 underneath defenders handle quick game. Best as a baseline call vs balanced 7v7 passing teams.",
    weaknesses: [
      "4 verts — three deep defenders against four vertical threats forces a coverage bust.",
      "Smash on the boundary — Cover 3's corner-flat conflict shows up the same way as in tackle.",
      "Curl-flat — the underneath flat defender can't cover both the curl and the flat receiver.",
      "Mesh and other in-breaking rubs at the hook level — the underneath zones are stretched horizontally.",
    ],
    defenders: [
      { id: "FL", x: -10, y: 4,  assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "HL", x: -4,  y: 5,  assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "HR", x:  4,  y: 5,  assignment: { kind: "zone", zoneId: "hook_r" } },
      { id: "FR", x: 10,  y: 4,  assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "CB", x: -12, y: 11, assignment: { kind: "zone", zoneId: "deep_third_l" } },
      { id: "FS", x:  0,  y: 13, assignment: { kind: "zone", zoneId: "deep_third_m" } },
      { id: "CB", x: 12,  y: 11, assignment: { kind: "zone", zoneId: "deep_third_r" } },
    ],
    zones: [
      { id: "flat_l",       kind: "ellipse", center: [-11, 5], size: [8,  8], label: "Flat L" },
      { id: "hook_l",       kind: "ellipse", center: [-4,  5], size: [6,  8], label: "Hook L" },
      { id: "hook_r",       kind: "ellipse", center: [ 4,  5], size: [6,  8], label: "Hook R" },
      { id: "flat_r",       kind: "ellipse", center: [11,  5], size: [8,  8], label: "Flat R" },
      { id: "deep_third_l", kind: "ellipse", center: [-10, 17], size: [10, 16], label: "Deep 1/3 L" },
      { id: "deep_third_m", kind: "ellipse", center: [ 0,  17], size: [10, 16], label: "Deep 1/3 M" },
      { id: "deep_third_r", kind: "ellipse", center: [10,  17], size: [10, 16], label: "Deep 1/3 R" },
    ],
  },
  {
    id: "f7-cover-2",
    name: "7v7 Zone · Cover 2",
    family: "scheme",
    variants: ["flag_7v7"],
    description: "7v7 Cover 2 — two safeties split the deep halves, five underneath in zones (two flats, three hooks).",
    body: "7v7 Cover 2 — two safeties split the deep halves, five underneath in zones (two flats, three hooks).",
    complexity: "basic",
    front: "7v7 Zone",
    coverage: "Cover 2",
    whenToUse: "Cover 2 shell with safeties splitting the deep halves and corners squatting in the flats — kills quick outs and hitches. Best in 7v7 when the offense lives in the sideline passing game.",
    weaknesses: [
      "Deep middle (no MLB to carry the seam) — 4 verts with a seam runner busts the coverage cleanly.",
      "Smash concept — corner over-the-top is the classic Cover 2 beater; the safety can't help in time.",
      "Drives between the hashes — the hook defender has too much real estate to cover.",
      "Quick crossers — Cover 2's underneath defenders trail picked-on routes.",
    ],
    defenders: [
      { id: "CB", x: -12, y: 5,  assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "HL", x: -5,  y: 5,  assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "HM", x:  0,  y: 5,  assignment: { kind: "zone", zoneId: "hook_m" } },
      { id: "HR", x:  5,  y: 5,  assignment: { kind: "zone", zoneId: "hook_r" } },
      { id: "CB", x: 12,  y: 5,  assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "FS", x: -7,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_l" } },
      { id: "SS", x:  7,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_r" } },
    ],
    zones: [
      { id: "flat_l", kind: "ellipse", center: [-12, 5], size: [6, 8], label: "Flat L" },
      { id: "hook_l", kind: "ellipse", center: [-5,  5], size: [6, 8], label: "Hook L" },
      { id: "hook_m", kind: "ellipse", center: [ 0,  5], size: [6, 8], label: "Hook M" },
      { id: "hook_r", kind: "ellipse", center: [ 5,  5], size: [6, 8], label: "Hook R" },
      { id: "flat_r", kind: "ellipse", center: [12,  5], size: [6, 8], label: "Flat R" },
      { id: "deep_half_l", kind: "ellipse", center: [-7.5, 17], size: [15, 16], label: "Deep 1/2 L" },
      { id: "deep_half_r", kind: "ellipse", center: [ 7.5, 17], size: [15, 16], label: "Deep 1/2 R" },
    ],
  },
  {
    id: "f7-tampa-2",
    name: "7v7 Zone · Tampa 2",
    family: "scheme",
    variants: ["flag_7v7"],
    description: "7v7 Tampa 2 — Cover 2 shell with the middle hook (M) carrying any vertical down the deep middle.",
    body: "7v7 Tampa 2 — Cover 2 shell with the middle hook (M) carrying any vertical down the deep middle. Effectively a 3-deep, 4-under look out of a 2-high disguise.",
    complexity: "advanced",
    front: "7v7 Zone",
    coverage: "Tampa 2",
    whenToUse: "Cover 2 shell with the middle hook defender sprinting to the deep middle to plug the seam. Best when your MLB has the speed to legitimately carry a vertical route — closes the Cover 2 deep-middle hole.",
    weaknesses: [
      "The 8-12yd middle hole the MLB just vacated — dig + crosser concepts attack exactly that void.",
      "Smash high-low — the corner-flat split still exists; the Cover 2 corner can't help on the corner route.",
      "Quick game while the MLB is mid-drop — the underneath middle is open for 1-2 seconds.",
      "Boundary-side vertical — the safety has to choose between the corner and the post.",
    ],
    defenders: [
      { id: "CB", x: -12, y: 5,  assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "HL", x: -5,  y: 5,  assignment: { kind: "zone", zoneId: "hook_l" } },
      { id: "M",  x:  0,  y: 6,  assignment: { kind: "zone", zoneId: "deep_middle" } },
      { id: "HR", x:  5,  y: 5,  assignment: { kind: "zone", zoneId: "hook_r" } },
      { id: "CB", x: 12,  y: 5,  assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "FS", x: -7,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_l" } },
      { id: "SS", x:  7,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_r" } },
    ],
    zones: [
      { id: "flat_l", kind: "ellipse", center: [-12, 5], size: [6, 8], label: "Flat L" },
      { id: "hook_l", kind: "ellipse", center: [-5,  5], size: [6, 8], label: "Hook L" },
      { id: "hook_r", kind: "ellipse", center: [ 5,  5], size: [6, 8], label: "Hook R" },
      { id: "flat_r", kind: "ellipse", center: [12,  5], size: [6, 8], label: "Flat R" },
      { id: "deep_half_l", kind: "ellipse", center: [-9, 17], size: [12, 16], label: "Deep 1/2 L" },
      { id: "deep_middle", kind: "ellipse", center: [ 0, 17], size: [6,  16], label: "Deep mid (M)" },
      { id: "deep_half_r", kind: "ellipse", center: [ 9, 17], size: [12, 16], label: "Deep 1/2 R" },
    ],
  },
  {
    id: "f7-cover-4",
    name: "7v7 Zone · Cover 4 Quarters",
    family: "scheme",
    variants: ["flag_7v7"],
    description: "7v7 Quarters — four deep defenders each take a quarter of the field, three underneath. Strong vs verticals; soft underneath.",
    body: "7v7 Quarters — four deep defenders each take a quarter of the field, three underneath. Strong vs verticals; soft underneath.",
    complexity: "intermediate",
    front: "7v7 Zone",
    coverage: "Cover 4",
    whenToUse: "Two-high quarters in 7v7 — four deep defenders match vertical releases, three underneath handle quick game. Best vs deep-shot 7v7 offenses or in must-have-yards situations where you need a hard ceiling.",
    weaknesses: [
      "Underneath quick game — only 3 underneath zones means the middle is open vs hitches and drag concepts.",
      "Mesh concept — picks at the crossers exploit the underneath man-match while safeties stay deep.",
      "Crossers / shallow drag — the underneath defenders are stretched thin horizontally.",
      "Heavy run — only 3 box defenders is a numbers disadvantage vs run-first offenses.",
    ],
    defenders: [
      { id: "FL", x: -10, y: 5,  assignment: { kind: "zone", zoneId: "curl_flat_l" } },
      { id: "M",  x:   0, y: 5,  assignment: { kind: "zone", zoneId: "hook_m" } },
      { id: "FR", x:  10, y: 5,  assignment: { kind: "zone", zoneId: "curl_flat_r" } },
      { id: "CB", x: -13, y: 11, assignment: { kind: "zone", zoneId: "deep_quarter_1" } },
      { id: "FS", x:  -5, y: 13, assignment: { kind: "zone", zoneId: "deep_quarter_2" } },
      { id: "SS", x:   5, y: 13, assignment: { kind: "zone", zoneId: "deep_quarter_3" } },
      { id: "CB", x:  13, y: 11, assignment: { kind: "zone", zoneId: "deep_quarter_4" } },
    ],
    zones: [
      { id: "curl_flat_l", kind: "ellipse", center: [-10, 5], size: [10, 8], label: "Curl/Flat L" },
      { id: "hook_m",      kind: "ellipse", center: [  0, 5], size: [8,  8], label: "Hook M" },
      { id: "curl_flat_r", kind: "ellipse", center: [ 10, 5], size: [10, 8], label: "Curl/Flat R" },
      { id: "deep_quarter_1", kind: "ellipse", center: [-11, 17], size: [8, 16], label: "Deep 1/4" },
      { id: "deep_quarter_2", kind: "ellipse", center: [ -4, 17], size: [6, 16], label: "Deep 1/4" },
      { id: "deep_quarter_3", kind: "ellipse", center: [  4, 17], size: [6, 16], label: "Deep 1/4" },
      { id: "deep_quarter_4", kind: "ellipse", center: [ 11, 17], size: [8, 16], label: "Deep 1/4" },
    ],
  },
  {
    id: "f7-cover-1",
    name: "7v7 Man · Cover 1",
    family: "scheme",
    variants: ["flag_7v7"],
    description: "7v7 man-free — six defenders in man on the six skill receivers, single-high FS over the top.",
    body: "7v7 man-free — six defenders in man on the six skill receivers, single-high FS over the top.",
    complexity: "basic",
    front: "7v7 Man",
    coverage: "Cover 1",
    whenToUse: "7v7 man coverage with one safety helping over the top — best vs balanced offenses when you trust your DBs in pure matchup football. The free safety bails out a deep shot on the worst matchup.",
    weaknesses: [
      "Picks / bunch concepts — natural rubs from mesh / smash / snag confuse the man switches.",
      "RB / TE on a LB or smaller DB — the matchup is consistently the offense's win.",
      "Verticals to your weakest DB — single-high safety can only help on one side.",
      "Hot routes vs blitz — when the rush gets there fast, the man underneath gives up easy completions.",
    ],
    manCoverage: true,
    defenders: [
      { id: "CB", x: -12, y: 5,  assignment: { kind: "man", target: "X" } },
      { id: "NB", x: -6,  y: 5,  assignment: { kind: "man", target: "H" } },
      { id: "LB", x:  0,  y: 4,  assignment: { kind: "man", target: "B" } },
      { id: "NB", x:  6,  y: 5,  assignment: { kind: "man", target: "S" } },
      { id: "CB", x: 12,  y: 5,  assignment: { kind: "man", target: "Z" } },
      { id: "SS", x:  4,  y: 6,  assignment: { kind: "man", target: "Y" } },
      { id: "FS", x:  0,  y: 13, assignment: { kind: "zone", zoneId: "deep_middle" } },
    ],
    zones: [
      { id: "deep_middle", kind: "ellipse", center: [0, 17], size: [20, 16], label: "Deep middle (FS)" },
    ],
  },
  {
    id: "f7-cover-0",
    name: "7v7 Man · Cover 0",
    family: "scheme",
    variants: ["flag_7v7"],
    description: "7v7 Cover 0 — every defender in pure man, no deep help. Rare, used to bait an aggressive throw or on critical down/distance.",
    body: "7v7 Cover 0 — every defender in pure man, no deep help. Rare, used to bait an aggressive throw or on critical down/distance.",
    complexity: "advanced",
    front: "7v7 Man",
    coverage: "Cover 0",
    whenToUse: "All-out pressure call — every defender is in man with NO safety help. Best on third-and-long when the offense is one-dimensional pass and you need a stop. Also useful in goal-line short-yardage when you need a body on every gap.",
    weaknesses: [
      "Hot routes / quick game — any 3-step throw beats the rush; the QB releases the ball before the pressure arrives.",
      "Picks and rubs from bunch / mesh — no safety help means a missed switch is a wide-open receiver.",
      "Mismatches anywhere — a slot WR on a LB or RB on a DB is a guaranteed completion.",
      "Deep shots — without ANY safety help, any 1-on-1 vertical win is a touchdown.",
    ],
    manCoverage: true,
    defenders: [
      { id: "CB", x: -12, y: 5, assignment: { kind: "man", target: "X" } },
      { id: "NB", x: -6,  y: 5, assignment: { kind: "man", target: "H" } },
      { id: "LB", x:  0,  y: 4, assignment: { kind: "man", target: "B" } },
      { id: "NB", x:  6,  y: 5, assignment: { kind: "man", target: "S" } },
      { id: "CB", x: 12,  y: 5, assignment: { kind: "man", target: "Z" } },
      { id: "SS", x:  6,  y: 6, assignment: { kind: "man", target: "Y" } },
      { id: "FS", x: -4,  y: 6, assignment: { kind: "spy", target: "Q" } },
    ],
    zones: [],
  },

  // ── Flag 6v6 ──────────────────────────────────────────────────────
  {
    id: "f6-cover-3",
    name: "6v6 Zone · Cover 3",
    family: "scheme",
    variants: ["flag_6v6"],
    description: "6v6 zone shell — 3 deep (two corners + free safety), 2 underneath (flat/hook on each side), one rusher staged behind the 7-yard rush line.",
    body: "6v6 zone shell — 3 deep (two corners + free safety), 2 underneath (flat/hook on each side), one rusher staged behind the 7-yard rush line.",
    complexity: "basic",
    front: "6v6 Zone",
    coverage: "Cover 3",
    whenToUse: "6v6 zone shell — three deep, three underneath. The default call vs balanced 6v6 offenses; covers the deep field without committing to man.",
    weaknesses: [
      "4 verts is impossible to defend perfectly with only 3 deep — the offense always has a numbers advantage downfield.",
      "Smash + curl-flat on the boundary — Cover 3's flat-defender conflict surfaces the same way as in 7v7.",
      "Quick crossers in the middle — the lone hook defender has too much horizontal space to cover.",
    ],
    defenders: [
      { id: "R",  x:  4,  y: 7,  assignment: { kind: "blitz", gap: "edge" } },
      { id: "FL", x: -8,  y: 4,  assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "FR", x:  8,  y: 4,  assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "CB", x: -11, y: 11, assignment: { kind: "zone", zoneId: "deep_third_l" } },
      { id: "FS", x:  0,  y: 13, assignment: { kind: "zone", zoneId: "deep_third_m" } },
      { id: "CB", x: 11,  y: 11, assignment: { kind: "zone", zoneId: "deep_third_r" } },
    ],
    zones: [
      { id: "flat_l", kind: "ellipse", center: [-9, 4], size: [8, 8], label: "Flat L" },
      { id: "flat_r", kind: "ellipse", center: [ 9, 4], size: [8, 8], label: "Flat R" },
      { id: "deep_third_l", kind: "ellipse", center: [-10, 17], size: [10, 16], label: "Deep 1/3 L" },
      { id: "deep_third_m", kind: "ellipse", center: [  0, 17], size: [10, 16], label: "Deep 1/3 M" },
      { id: "deep_third_r", kind: "ellipse", center: [ 10, 17], size: [10, 16], label: "Deep 1/3 R" },
    ],
  },
  {
    id: "f6-cover-2",
    name: "6v6 Zone · Cover 2",
    family: "scheme",
    variants: ["flag_6v6"],
    description: "6v6 Cover 2 — two safeties split the deep halves, three underneath in zones (two flats + a middle hook), one rusher staged behind the 7-yard rush line.",
    body: "6v6 Cover 2 — two safeties split the deep halves, three underneath in zones (two flats + a middle hook), one rusher staged behind the 7-yard rush line.",
    complexity: "basic",
    front: "6v6 Zone",
    coverage: "Cover 2",
    whenToUse: "6v6 with two safeties splitting the deep halves and corners squatting in flats — kills perimeter quick game. Best when the offense lives on quick outs and stop routes.",
    weaknesses: [
      "Deep middle — no MLB to carry the seam; 4-vert / seam concepts find the void between the safeties.",
      "Smash high-low on the corner — Cover 2 corner can't cover both the corner route and the flat.",
      "Drives between the hashes — only one underneath defender to cover the entire middle.",
    ],
    defenders: [
      { id: "R",  x:  4,  y: 7,  assignment: { kind: "blitz", gap: "edge" } },
      { id: "CB", x: -10, y: 5,  assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "HM", x:  0,  y: 5,  assignment: { kind: "zone", zoneId: "hook_m" } },
      { id: "CB", x: 10,  y: 5,  assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "FS", x: -6,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_l" } },
      { id: "SS", x:  6,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_r" } },
    ],
    zones: [
      { id: "flat_l", kind: "ellipse", center: [-10, 5], size: [8, 8], label: "Flat L" },
      { id: "hook_m", kind: "ellipse", center: [  0, 5], size: [8, 8], label: "Hook M" },
      { id: "flat_r", kind: "ellipse", center: [ 10, 5], size: [8, 8], label: "Flat R" },
      { id: "deep_half_l", kind: "ellipse", center: [-7, 17], size: [14, 16], label: "Deep 1/2 L" },
      { id: "deep_half_r", kind: "ellipse", center: [ 7, 17], size: [14, 16], label: "Deep 1/2 R" },
    ],
  },
  {
    id: "f6-cover-1",
    name: "6v6 Man · Cover 1",
    family: "scheme",
    variants: ["flag_6v6"],
    description: "6v6 man-free — four defenders in man on the four skill receivers, one free safety deep, one rusher staged behind the 7-yard rush line.",
    body: "6v6 man-free — four defenders in man on the four skill receivers, one free safety deep, one rusher staged behind the 7-yard rush line.",
    complexity: "basic",
    front: "6v6 Man",
    coverage: "Cover 1",
    whenToUse: "6v6 man with a free safety over the top — best vs balanced offenses when you trust your DBs in matchup football and need an extra body in the run-pass conflict.",
    weaknesses: [
      "Bunch / picks — natural rubs from mesh / snag confuse the man switches.",
      "RB / TE matchups on a LB — the smaller pass-catcher wins on a route.",
      "Deep verticals to your weakest DB — single-high means no double on the threat.",
    ],
    manCoverage: true,
    defenders: [
      { id: "R",  x:  4,  y: 7,  assignment: { kind: "blitz", gap: "edge" } },
      { id: "CB", x: -10, y: 5,  assignment: { kind: "man", target: "X" } },
      { id: "NB", x: -4,  y: 5,  assignment: { kind: "man", target: "Y" } },
      { id: "NB", x:  4,  y: 5,  assignment: { kind: "man", target: "S" } },
      { id: "CB", x:  10, y: 5,  assignment: { kind: "man", target: "Z" } },
      { id: "FS", x:  0,  y: 12, assignment: { kind: "zone", zoneId: "deep_middle" } },
    ],
    zones: [
      { id: "deep_middle", kind: "ellipse", center: [0, 17], size: [20, 16], label: "Deep middle (FS)" },
    ],
  },
  {
    id: "f6-cover-0",
    name: "6v6 Man · Cover 0",
    family: "scheme",
    variants: ["flag_6v6"],
    description: "6v6 Cover 0 — every defender in pure man, no deep help. One rusher (staged behind the 7-yard rush line) disrupts the QB.",
    body: "6v6 Cover 0 — every defender in pure man, no deep help. One rusher (staged behind the 7-yard rush line) disrupts the QB; used to bait an aggressive throw or on critical down/distance.",
    complexity: "advanced",
    front: "6v6 Man",
    coverage: "Cover 0",
    whenToUse: "All-out pressure with NO safety help — every defender is in man. Best on third-and-long when you need a sack or a stop. Risky on neutral downs.",
    weaknesses: [
      "Hot routes / quick game — any 3-step throw beats the rush.",
      "Picks and rubs — no safety means a missed switch is a touchdown.",
      "Any 1-on-1 deep win — without a safety, vertical mismatches are uncontested.",
    ],
    manCoverage: true,
    defenders: [
      { id: "R",  x:  4,  y: 7,  assignment: { kind: "blitz", gap: "edge" } },
      { id: "CB", x: -10, y: 5,  assignment: { kind: "man", target: "X" } },
      { id: "NB", x: -4,  y: 5,  assignment: { kind: "man", target: "Y" } },
      { id: "NB", x:  4,  y: 5,  assignment: { kind: "man", target: "S" } },
      { id: "CB", x:  10, y: 5,  assignment: { kind: "man", target: "Z" } },
      { id: "SS", x:  0,  y: 6,  assignment: { kind: "man", target: "B" } },
    ],
    zones: [],
  },

  // ── Flag 5v5 ──────────────────────────────────────────────────────
  {
    id: "f5-cover-3",
    name: "5v5 Zone · Cover 3",
    family: "scheme",
    variants: ["flag_5v5"],
    description: "5v5 zone shell — 3 deep (two corners + free safety) and 2 underneath (flat/hook on each side).",
    body: "5v5 zone shell — 3 deep (two corners + free safety) and 2 underneath (flat/hook on each side).",
    complexity: "basic",
    front: "5v5 Zone",
    coverage: "Cover 3",
    whenToUse: "5v5 zone shell — 3 deep (corners + free safety on the hashes) and 2 underneath flats. The baseline call vs balanced 5v5 offenses. Best when you want to cap chunk plays without committing to man.",
    weaknesses: [
      "4 receivers running deep stretches your 3 deep defenders — there's no helping the seam between the corner and the safety.",
      "Smash on the boundary — Cover 3's corner-flat conflict surfaces the same way as in 7v7 and tackle.",
      "Mesh / shallow crossers — two underneath flats are stretched thin horizontally; crossers hit the void at 5-6yd depth.",
    ],
    defenders: [
      { id: "FL", x: -7,  y: 4,  assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "FR", x:  7,  y: 4,  assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "CB", x: -10, y: 10, assignment: { kind: "zone", zoneId: "deep_third_l" } },
      { id: "FS", x:  0,  y: 12, assignment: { kind: "zone", zoneId: "deep_third_m" } },
      { id: "CB", x: 10,  y: 10, assignment: { kind: "zone", zoneId: "deep_third_r" } },
    ],
    zones: [
      { id: "flat_l", kind: "ellipse", center: [-8, 4], size: [10, 8], label: "Flat L" },
      { id: "flat_r", kind: "ellipse", center: [ 8, 4], size: [10, 8], label: "Flat R" },
      { id: "deep_third_l", kind: "ellipse", center: [-9, 17], size: [9, 16], label: "Deep 1/3 L" },
      { id: "deep_third_m", kind: "ellipse", center: [ 0, 17], size: [9, 16], label: "Deep 1/3 M" },
      { id: "deep_third_r", kind: "ellipse", center: [ 9, 17], size: [9, 16], label: "Deep 1/3 R" },
    ],
  },
  {
    id: "f5-cover-1",
    name: "5v5 Man · Cover 1",
    family: "scheme",
    variants: ["flag_5v5"],
    description: "5v5 man — four defenders in man on the four skill players, one free safety deep.",
    body: "5v5 man — four defenders in man on the four skill players, one free safety deep.",
    complexity: "basic",
    front: "5v5 Man",
    coverage: "Cover 1",
    whenToUse: "5v5 man coverage with a free safety helping over the top — best vs balanced offenses when you trust your matchups. The free safety is your insurance against the deep shot.",
    weaknesses: [
      "Picks / bunch concepts — natural rubs from mesh / smash / snag confuse the man switches.",
      "RB matchup on a defender who isn't your best cover guy — the smaller, quicker target wins.",
      "Vertical to the weakest matchup — single-high safety can only help on one side.",
      "Hot routes vs rush — when pressure gets there fast, the man defender gives up an easy completion.",
    ],
    manCoverage: true,
    defenders: [
      { id: "CB", x: -8,  y: 5,  assignment: { kind: "man", target: "X" } },
      // CORRECTED 2026-05-26 — was H/S which don't exist in flag_5v5
      // (Spread Doubles roster is X, Y, Z, C; no inside slots labeled H/S).
      // Now covers @C (eligible center) and @Y (slot/back hybrid).
      { id: "NB", x: -3,  y: 5,  assignment: { kind: "man", target: "C" } },
      { id: "NB", x:  3,  y: 5,  assignment: { kind: "man", target: "Y" } },
      { id: "CB", x:  8,  y: 5,  assignment: { kind: "man", target: "Z" } },
      { id: "FS", x:  0,  y: 12, assignment: { kind: "zone", zoneId: "deep_middle" } },
    ],
    zones: [
      { id: "deep_middle", kind: "ellipse", center: [0, 17], size: [20, 16], label: "Deep middle (FS)" },
    ],
  },
  // ── 5v5 rushing defenses (added 2026-05-26) ────────────────────────
  //
  // The 5v5 catalog previously had only "drop everyone" defenses (Cover
  // 1 + Cover 3), which is unusual at every level of real flag football.
  // Most 5v5 calls include 1 rusher; aggressive calls send 2. Per USA
  // Football's 5v5 rulebook the rusher must be behind the 7-yard line
  // pre-snap; defenders in front of the line can't cross the LOS until
  // the ball leaves the QB's hand. The R/R2 labels render with a
  // distinct color (slate) so coaches can spot rushers immediately, and
  // the rush line itself draws automatically on defense pages.
  //
  // Naming follows the existing pattern (`<variant> <type> · <coverage>`)
  // with the rusher count + "Blitz" suffix added where it isn't implicit
  // in the coverage shell. Cover 0 already implies all-out pressure;
  // Cover 2 with a rusher is a standard balanced call.
  {
    id: "f5-cover-0",
    name: "5v5 Man · Cover 0 (1 Rush)",
    family: "scheme",
    variants: ["flag_5v5"],
    description: "5v5 all-out pressure — 1 rusher staged behind the 7-yard rush line, 4 in man across the board, no deep help.",
    body: "5v5 all-out pressure — one rusher staged behind the 7-yard rush line attacks the QB; the other four defenders are in pure man on the four eligible receivers. NO safety help; any 1-on-1 deep win is a touchdown. Use when you need a sack or a stop on critical down/distance and trust your DBs to win their reps.",
    complexity: "advanced",
    front: "5v5 Man",
    coverage: "Cover 0 Blitz",
    whenToUse: "Third-and-long with the offense in passing posture. The rusher pressures the QB into a quick decision; the man defenders need to win their reps before the QB scrambles. Rare on neutral downs — the deep ball is uncontested.",
    weaknesses: [
      "Hot routes / quick game — any 3-step throw beats the rush; the QB releases before the rusher arrives.",
      "Picks and rubs from mesh / snag — no safety help means a missed switch is a wide-open receiver.",
      "Any 1-on-1 deep win — without ANY safety help, vertical mismatches go uncontested.",
    ],
    manCoverage: true,
    defenders: [
      { id: "R",  x:  0,  y: 7, assignment: { kind: "blitz", gap: "edge" } },
      { id: "CB", x: -8,  y: 5, assignment: { kind: "man", target: "X" } },
      { id: "NB", x: -3,  y: 5, assignment: { kind: "man", target: "C" } },
      { id: "NB", x:  3,  y: 5, assignment: { kind: "man", target: "Y" } },
      { id: "CB", x:  8,  y: 5, assignment: { kind: "man", target: "Z" } },
    ],
    zones: [],
  },
  {
    id: "f5-cover-2",
    name: "5v5 Zone · Cover 2 (1 Rush)",
    family: "scheme",
    variants: ["flag_5v5"],
    description: "5v5 Cover 2 with one rusher — two deep halves, two flat corners, one rusher staged behind the 7-yard rush line. The deep shell traded the middle hook for pressure on the QB.",
    body: "5v5 Cover 2 with a rusher — two safeties split the deep halves of the field, two corners squat the flats, one rusher (staged behind the 7-yard rush line) attacks the QB. With only 5 defenders total in 5v5, the trade-off is the middle hook window — the offense gets a free 5–8yd middle if they hit it before the rusher arrives.",
    complexity: "intermediate",
    front: "5v5 Zone",
    coverage: "Cover 2",
    whenToUse: "5v5 balanced look — pressure with one rusher while still capping deep with two safeties. Best vs offenses that live on quick perimeter game; the two-safety shell discourages the deep shot.",
    weaknesses: [
      "Middle hook window — no underneath defender between the corners; crossers / drag / dig at 5–8yd are open until the rusher arrives.",
      "Smash on the boundary — Cover 2 corner-to-flat conflict surfaces here the same way as in 7v7.",
      "4 verts from a spread look — only 2 deep defenders covering the seams + numbers.",
    ],
    defenders: [
      { id: "R",  x:  0,  y: 7,  assignment: { kind: "blitz", gap: "edge" } },
      { id: "CB", x: -10, y: 4,  assignment: { kind: "zone", zoneId: "flat_l" } },
      { id: "CB", x:  10, y: 4,  assignment: { kind: "zone", zoneId: "flat_r" } },
      { id: "FS", x: -6,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_l" } },
      { id: "SS", x:  6,  y: 12, assignment: { kind: "zone", zoneId: "deep_half_r" } },
    ],
    zones: [
      { id: "flat_l", kind: "ellipse", center: [-10, 4], size: [9, 8], label: "Flat L" },
      { id: "flat_r", kind: "ellipse", center: [ 10, 4], size: [9, 8], label: "Flat R" },
      { id: "deep_half_l", kind: "ellipse", center: [-7, 17], size: [14, 16], label: "Deep 1/2 L" },
      { id: "deep_half_r", kind: "ellipse", center: [ 7, 17], size: [14, 16], label: "Deep 1/2 R" },
    ],
  },
  {
    id: "f5-2-rush-zone",
    name: "5v5 Zone · 2-1-2 (2 Rush)",
    family: "scheme",
    variants: ["flag_5v5"],
    description: "5v5 aggressive zone — 2 rushers staged behind the 7-yard line, 1 mid-zone spy, 2 deep safeties. Highest-risk pressure look in 5v5.",
    body: "Two rushers attack the QB from behind the 7-yard rush line; one defender plays a mid-zone spy (watching the QB scramble + the underneath middle), two safeties split the deep halves. Aggressive — only 3 defenders in coverage against 4 receivers, so the offense has a numerical advantage somewhere. Use sparingly to disrupt rhythm.",
    complexity: "advanced",
    front: "5v5 Zone",
    coverage: "2-1-2 Blitz",
    whenToUse: "Pressure call to disrupt a hot QB or force a 4th down. The two rushers cut the QB's throwing window in half; the spy takes away the scramble. Don't sit in this — it's a change-up, not a base call.",
    weaknesses: [
      "4 receivers vs 3 coverage defenders — the offense has someone uncovered every snap; the rush has to win or the QB finds the open man.",
      "Quick mesh / drive routes — only one underneath defender can't cover both sides of the field.",
      "Vertical from the slot — the safeties have to widen for outside verts; an inside seam splits them.",
    ],
    defenders: [
      { id: "R",  x: -4, y: 7,  assignment: { kind: "blitz", gap: "edge" } },
      { id: "R2", x:  4, y: 7,  assignment: { kind: "blitz", gap: "edge" } },
      { id: "HM", x:  0, y: 5,  assignment: { kind: "zone", zoneId: "hook_m" } },
      { id: "FS", x: -6, y: 12, assignment: { kind: "zone", zoneId: "deep_half_l" } },
      { id: "SS", x:  6, y: 12, assignment: { kind: "zone", zoneId: "deep_half_r" } },
    ],
    zones: [
      { id: "hook_m", kind: "ellipse", center: [ 0, 5], size: [12, 8], label: "Hook M (spy)" },
      { id: "deep_half_l", kind: "ellipse", center: [-7, 17], size: [14, 16], label: "Deep 1/2 L" },
      { id: "deep_half_r", kind: "ellipse", center: [ 7, 17], size: [14, 16], label: "Deep 1/2 R" },
    ],
  },
];
