/**
 * Defense starter formations — the bridge between a seeded `formations` row
 * and the catalog alignment it was generated from.
 *
 * A defensive formation stores BODIES ONLY, the same contract as offense:
 * the coverage's zones and assignments belong to the play, not the formation.
 * But when a coach starts a NEW play from a starter there is no existing work
 * to destroy, so we install that coverage's zones too — a coach picking
 * "Cover 2" should get a Cover 2 picture, not seven bare triangles.
 *
 * That requires resolving a seed row back to its alignment. `semantic_key` is
 * the only durable link (row ids are regenerated by the seed migration), and
 * slugging is lossy — "4-3 Over" → "4_3_over" can't be reversed. So instead of
 * parsing, we re-derive the key for every catalog alignment and match. The key
 * format lives HERE and is imported by both scripts/regen-formation-seeds.ts
 * (which writes the keys) and the app (which reads them), so the two cannot
 * drift apart.
 */

import {
  DEFENSIVE_ALIGNMENTS,
  type DefensiveAlignment,
} from "./defensiveAlignments";

export type StarterStrength = "left" | "right" | "balanced";

export type ResolvedDefenseStarter = {
  alignment: DefensiveAlignment;
  strength: StarterStrength;
};

/** Lowercase + collapse non-alphanumerics. Shared by the key builder so the
 *  script and the app slug identically. */
export function slugifyDefensePart(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

/**
 * The `semantic_key` for a seeded defensive formation. Stable across seed
 * regens — this is what survives when the migration deletes and re-inserts
 * the seed rows with fresh uuids.
 */
export function defenseStarterSemanticKey(
  alignment: Pick<DefensiveAlignment, "front" | "coverage" | "variant">,
  strength: StarterStrength,
): string {
  return [
    "catalog_def",
    slugifyDefensePart(alignment.front),
    slugifyDefensePart(alignment.coverage),
    slugifyDefensePart(alignment.variant),
    strength,
  ].join("_");
}

/** semantic_key → alignment, built once at module load. */
const BY_KEY: Map<string, ResolvedDefenseStarter> = (() => {
  const m = new Map<string, ResolvedDefenseStarter>();
  for (const alignment of DEFENSIVE_ALIGNMENTS) {
    for (const strength of ["balanced", "right", "left"] as const) {
      const key = defenseStarterSemanticKey(alignment, strength);
      // A collision would mean two catalog alignments share front+coverage+
      // variant, which findDefensiveAlignment already treats as impossible.
      if (!m.has(key)) m.set(key, { alignment, strength });
    }
  }
  return m;
})();

/**
 * Resolve a seeded formation's `semantic_key` back to its catalog alignment.
 * Returns null for user-authored formations (`custom_*`, `seeded_*`) and for
 * offense seeds — callers treat null as "no zones to install", which is the
 * correct behavior for a formation a coach drew themselves.
 */
export function resolveDefenseStarter(
  semanticKey: string | null | undefined,
): ResolvedDefenseStarter | null {
  if (!semanticKey) return null;
  return BY_KEY.get(semanticKey) ?? null;
}

/** True when this key names a catalog-derived defensive starter. */
export function isDefenseStarterKey(semanticKey: string | null | undefined): boolean {
  return resolveDefenseStarter(semanticKey) !== null;
}
